from __future__ import annotations

from typing import Any


COMMON_DISPLAY_LABELS = {
    "created": "已创建",
    "intake_validated": "需求已校验",
    "searching": "检索中",
    "screening": "筛选中",
    "extracting": "抽取中",
    "mapping_entities": "实体映射中",
    "scoring": "评分中",
    "report_drafting": "报告撰写中",
    "under_review": "复核中",
    "completed": "已完成",
    "blocked": "阻塞",
    "failed": "失败",
    "cancelled": "已取消",
    "archived": "已归档",
    "draft": "草稿",
    "reviewable": "可复核",
    "published": "已发布",
    "c_open": "开放检索研究",
    "c_open_with_seed": "带种子资料的开放研究",
    "c_paper": "研报资料研究",
    "c_hybrid": "混合资料研究",
    "c_paper_scoring_ready": "研报研究/可评分",
    "needs_problem_rewrite": "研究问题待重写",
    "freshness_first": "新鲜度优先",
    "balanced": "平衡策略",
    "accuracy_first": "准确性优先",
    "none": "无",
    "papers_folder": "研报文件夹",
    "research_db_reference": "研究库参考",
    "core_evidence": "核心证据",
    "context_only": "背景证据",
    "early_signal": "早期信号",
    "early_signal_candidate": "早期信号候选",
    "reference_only": "仅参考",
    "pass_core": "通过核心评分门槛",
    "pass_context": "仅作背景参考",
    "pass_early_signal": "仅进入早期信号",
    "pass_reference": "仅参考通过",
    "reject_core": "不进入核心评分",
    "core_eligible": "可进入核心评分",
    "early_signal_only": "只用于早期信号",
    "excluded_from_scoring": "不进入评分",
    "pending": "待复核",
    "pass": "已通过",
    "pass_with_note": "通过/有备注",
    "weak_source_only": "仅弱来源",
    "duplicate": "重复来源",
    "paywalled": "付费墙限制",
    "stale": "资料陈旧",
    "conflict": "来源冲突",
    "reject": "已拒绝",
    "warning": "需注意",
    "fail": "未通过",
    "not_applicable": "不适用",
    "positive": "利多",
    "negative": "利空",
    "mixed": "多空混合",
    "neutral": "中性",
    "security": "证券",
    "etf": "ETF",
    "futures_contract": "期货合约",
    "spread": "价差",
    "basket": "组合观察篮子",
    "external_watch": "外部观察项",
    "listed": "上市公司",
    "private_subsidiary": "非上市子公司",
    "private": "非上市公司",
    "linked": "已链接",
    "external_only": "仅外部链接",
    "needs_company_profile": "待补公司页",
    "needs_evidence": "待补证据",
    "pdf_direct": "PDF 原文抽取",
    "web_fetch": "网页抽取",
    "structured_extraction": "结构化原文抽取",
    "template_estimate": "模板估算",
    "inferred": "推算",
    "unknown": "未标明",
    "C_INTAKE_CONTRACT_V1": "入口合同 v1",
    "product_material": "产品/材料",
    "company": "公司",
    "segment": "环节",
    "strong": "强",
    "medium": "中",
    "weak": "弱",
    "noise": "噪声",
    "high_priority_for_scoring": "高优先级评分",
    "high_priority_for_followup": "高优先级跟进",
    "high_priority": "高优先级",
    "medium_priority_for_followup": "中优先级跟进",
    "medium_priority": "中优先级",
    "low_priority_watch": "低优先级观察",
    "low_priority": "低优先级",
    "research_only_insufficient_data": "仅研究/证据不足",
    "research_only_literature_review_complete": "研究型综述完成",
    "market_linked": "市场/标的相关",
    "theory_research": "理论/研究型",
    "complete": "完整",
    "needs_more_sources": "需补来源",
    "literature_evidence": "文献证据",
    "definition_boundary": "定义边界",
    "value_chain": "价值链",
    "methodology": "方法口径",
    "counter_evidence": "反方证据",
    "research_data": "研究数据",
    "synthetic_fixture": "合成示例夹具",
    "scoring_ready": "可评分",
    "scoring_limited": "有限评分",
    "evidence_supported": "证据支持",
    "scored": "已评分",
    "scoring_blocked": "评分阻塞",
    "ready": "就绪",
    "limited": "有限",
    "missing": "缺失",
    "conflict_blocked": "冲突阻塞",
    "available": "可用",
    "estimated": "估算",
    "conflicting": "冲突",
    "insufficient_evidence": "证据不足",
    "superseded": "已被替代",
    "accepted": "已采纳",
    "rejected": "已拒绝",
    "not_scored": "未评分",
    "unrated": "未评级",
    "unrated_insufficient_evidence": "未评级/证据不足",
    "valid": "有效",
    "review_required": "需要复核",
    "high_confidence": "高置信度",
    "medium_confidence": "中等置信度",
    "provisional": "临时评分/待补证",
    "supported": "已支持",
    "partially_supported": "部分支持",
    "unsupported": "未支持",
    "needs_review": "待复核",
    "verified": "已验证",
    "open": "待处理",
    "in_review": "复核中",
    "resolved": "已解决",
    "waived": "已豁免",
    "reopened": "重新打开",
    "limits_scoring": "限制评分",
    "selected": "已选证据",
    "used_in_factor": "进入因子计算",
    "candidate": "候选证据",
    "stale_only": "仅过期证据支持",
    "conflict_unresolved": "证据冲突未解决",
    "blocked_by_conflict": "因冲突阻断",
    "available_text_only": "文本证据可用",
    "manual_fixture": "人工合成示例",
    "synthetic_lead_time": "合成交期",
    "synthetic_spot_quote_qoq": "合成现货报价环比",
    "synthetic_supplier_count": "合成供应商数量",
    "synthetic_revenue_exposure": "合成收入暴露代理",
    "capacity_change": "产能变化",
    "capacity": "产能",
    "price": "价格",
    "13f_recalc": "13F 持仓复算证据",
    "aws_profit": "AWS 利润证据",
    "capex": "资本开支证据",
    "capex_guidance": "资本开支指引证据",
    "cloud_revenue": "云收入证据",
    "company_ir": "公司 IR 证据",
    "counter_flow": "反向资金流证据",
    "derivatives_recalc": "衍生品仓位复算证据",
    "etf_flow": "ETF 资金流证据",
    "etf_return": "ETF 收益动量证据",
    "etf_valuation": "ETF 估值拥挤证据",
    "etf_weight": "ETF 权重证据",
    "foreign_flow_counter": "外资流出反方证据",
    "foreign_flow_positive": "外资流入证据",
    "hedge_fund_positioning": "对冲基金仓位证据",
    "index_weight": "指数权重证据",
    "japan_flow_dataset": "日本资金流数据证据",
    "market_price": "市场价格证据",
    "positioning_survey": "资金经理调查证据",
    "manual_verified_fact": "人工核验证据",
    "长期序列数据证据": "长期序列数据证据",
    "结构化表格证据": "结构化表格证据",
    "客户验证证据": "客户验证证据",
    "价格和市场空间证据": "价格和市场空间证据",
    "技术切换和产能证据": "技术切换和产能证据",
    "材料和工艺证据": "材料和工艺证据",
    "公开来源证据": "公开来源证据",
    "A/B 行研镜像证据": "A/B 行研镜像证据",
    "人工核验摘录证据": "人工核验摘录证据",
    "route_to_data_point": "进入数据点",
    "route_to_supplement_request": "进入补证请求",
    "merged_to_entity": "已合并为规范实体",
    "p0": "P0",
    "p1": "P1",
    "p2": "P2",
    "yellow": "黄色",
    "red": "红色",
    "queued": "排队中",
    "rendering_html": "生成 HTML 中",
    "rendering_assets": "生成资产中",
    "rendering_pdf": "生成 PDF 中",
    "expired": "已过期",
    "pdf": "PDF",
    "run_report": "单次扫描报告",
    "GREEN": "绿色",
    "YELLOW": "黄色",
    "RED": "红色",
}

CLIENT_DISPLAY_LABEL_KEYS = (
    "core_evidence", "context_only", "early_signal", "pass_core", "pass_context",
    "pass_early_signal", "reject_core", "core_eligible", "early_signal_only",
    "excluded_from_scoring", "pending", "pass", "pass_with_note", "weak_source_only",
    "duplicate", "paywalled", "stale", "conflict", "reject", "warning", "fail",
    "not_applicable", "positive", "negative", "mixed", "neutral", "pdf_direct",
    "web_fetch", "structured_extraction", "template_estimate", "inferred", "unknown",
)
CLIENT_DISPLAY_LABELS = {key: COMMON_DISPLAY_LABELS[key] for key in CLIENT_DISPLAY_LABEL_KEYS}


def display_label(value: Any) -> Any:
    if value is None:
        return "无"
    return COMMON_DISPLAY_LABELS.get(str(value), value)
