from __future__ import annotations

"""Run16 AI-application subsector research ledger and public narrative.

The ledger separates three quantities that are often confused in AI research:
product deployment/adoption, recognised AI-related revenue, and the broader
addressable workflow spend.  A conversion ratio is only shown when numerator
and denominator share the same market definition.
"""

from typing import Any, Mapping


def _cite(ref: str) -> str:
    return f"^src:source_ref:{ref}"


APPLICATION_INDUSTRY_SOURCES: tuple[dict[str, Any], ...] = (
    {
        "id": "I01",
        "source_channel": "web",
        "source_tier": "academic_primary",
        "publisher": "Stanford Institute for Human-Centered AI",
        "date": "2026-04-01",
        "title": "The 2026 AI Index Report - Economy",
        "title_zh": "2026年人工智能指数报告：经济与企业采用",
        "language": "en",
        "excerpt": "Organizational AI adoption reached 88% in 2025, while agent deployment remained in single digits in almost all functions.",
        "excerpt_zh": "2025年组织采用AI的比例达到88%，但在几乎所有职能中，真正部署智能体的比例仍为个位数。",
        "url": "https://hai.stanford.edu/ai-index/2026-ai-index-report/economy",
        "independence_key": "stanford_ai_index_2026_economy",
        "independence_rationale": "斯坦福HAI年度独立研究；采用率与智能体部署率来自同一年度报告，不拆成多条独立证据。",
        "candidates": ["all"],
        "entity_key": "ai_application_subsectors",
        "metric": "企业AI采用与智能体落地阶段",
        "claim_zh": "企业已经普遍使用AI，但能够跨系统执行任务的智能体仍处早期；‘用过AI’不能等同于企业已经为可执行工作流大规模付费。",
        "counterevidence_zh": "全球组织样本不能直接代表中国市场，也不能证明任一A股公司的合同或收入。",
        "uses": ["market_stage", "conversion_boundary"],
    },
    {
        "id": "I02",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-05-18",
        "title": "从基模到应用：AI云服务迎来新的增长机遇",
        "url": "https://www.idc.com/resource-center/blog/%E4%BB%8E%E5%9F%BA%E6%A8%A1%E5%88%B0%E5%BA%94%E7%94%A8-%E5%85%A8%E9%9D%A2%E6%99%BA%E8%83%BD%E4%BD%93%E5%8C%96%EF%BC%9Aai%E4%BA%91%E6%9C%8D%E5%8A%A1%E8%BF%8E%E6%9D%A5%E6%96%B0%E7%9A%84%E5%A2%9E/",
        "independence_key": "idc_china_public_cloud_ai_applications_2025",
        "independence_rationale": "IDC对2025年中国公有云AI应用服务的独立市场跟踪。",
        "candidates": ["百度智能云", "阿里云", "腾讯云", "华为云"],
        "entity_key": "ai_application_subsectors",
        "metric": "中国公有云AI应用服务收入",
        "claim_zh": "2025年中国公有云AI应用服务收入为137.3亿元，百度智能云份额30.7%居首；该口径覆盖客服、内容创作、知识管理等多种应用，证明企业应用已形成收入，但不能拆成单个细分行业规模。",
        "counterevidence_zh": "公有云口径不含大量私有化部署和独立SaaS，也不能与某一家应用公司的收入直接相减。",
        "uses": ["market_size", "competition"],
    },
    {
        "id": "I03",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-06-08",
        "title": "ERP的下一站，是会执行的AI",
        "url": "https://www.idc.com/resource-center/blog/erp%E7%9A%84%E4%B8%8B%E4%B8%80%E7%AB%99%EF%BC%8C%E6%98%AF%E4%BC%9A%E6%89%A7%E8%A1%8C%E7%9A%84ai/",
        "independence_key": "idc_china_ai_enabled_erp_2025",
        "independence_rationale": "IDC中国AI增强ERP市场份额研究，明确排除传统ERP收入。",
        "candidates": ["用友网络", "鼎捷数智", "金蝶国际"],
        "entity_key": "ai_application_subsectors",
        "metric": "AI增强ERP收入与产品边界",
        "claim_zh": "2025年中国AI增强企业级ERP收入为3.157亿美元、同比增长96.1%；统计只含AI产品、能力或模块收入，不含传统ERP，说明该细分已经从试点进入加速采购。",
        "counterevidence_zh": "行业收入仍不等于厂商已确认的AI收入；实施、验收、权限治理和持续运营成本仍决定利润。",
        "uses": ["market_size", "market_stage", "product_boundary"],
    },
    {
        "id": "I04",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2025-08-07",
        "title": "IDC中国数字金融论坛：金融生成式AI平台与应用",
        "url": "https://event-web.idc.com/72008/index.html",
        "independence_key": "idc_china_financial_genai_2024_2027",
        "independence_rationale": "IDC金融生成式AI平台和应用同口径市场测算与预测。",
        "candidates": ["同花顺", "恒生电子", "宇信科技", "东方财富"],
        "entity_key": "ai_application_subsectors",
        "metric": "金融生成式AI平台及应用收入",
        "claim_zh": "中国金融生成式AI平台及应用市场由2024年的9.14亿元预计增至2027年的35.09亿元；2024年收入仅相当于2027年预测终点的26.05%，但这不是当前未转化市场比例。",
        "counterevidence_zh": "口径含基础模型、平台、应用、咨询和定制IT服务，不能全部映射为金融软件公司的高毛利订阅。",
        "uses": ["market_size", "forecast", "conversion_boundary"],
    },
    {
        "id": "I05",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-07-01",
        "title": "中国基于大模型的安全运营平台市场份额，2025",
        "url": "https://www.idc.com/resource-center/blog/resource-region/3_328/page/2/",
        "independence_key": "idc_china_llm_security_operations_2025",
        "independence_rationale": "IDC对中国大模型安全运营平台的独立市场跟踪。",
        "candidates": ["深信服", "奇安信", "启明星辰", "绿盟科技", "安恒信息"],
        "entity_key": "ai_application_subsectors",
        "metric": "大模型安全运营平台收入与竞争",
        "claim_zh": "2025年中国基于大模型的安全运营平台收入达到15亿元、同比增长144%；阿里巴巴、深信服、360、启明星辰、绿盟科技和安恒信息处于主要厂商行列。",
        "counterevidence_zh": "IDC公开摘要没有给出各厂商份额，不能据此计算CR3；产品收入还需与传统网安和项目服务拆分。",
        "uses": ["market_size", "competition", "market_stage"],
    },
    {
        "id": "I06",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-04-21",
        "title": "医疗大模型的下一站：智能体正在重写医院软件",
        "url": "https://www.idc.com/resource-center/blog/%E5%8C%BB%E7%96%97%E5%A4%A7%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E4%B8%80%E7%AB%99%EF%BC%9A%E6%99%BA%E8%83%BD%E4%BD%93%E6%AD%A3%E5%9C%A8%E9%87%8D%E5%86%99%E5%8C%BB/",
        "independence_key": "idc_china_ai_medical_software_2025_2030",
        "independence_rationale": "IDC医疗软件同口径市场预测与技术评测。",
        "candidates": ["科大讯飞", "卫宁健康", "创业慧康", "嘉和美康", "东软集团"],
        "entity_key": "ai_application_subsectors",
        "metric": "AI医疗应用软件收入与渗透率",
        "claim_zh": "2025年中国AI+医疗应用软件收入35.4亿元，IDC预计2030年达到140.0亿元、渗透率44.7%；2025年收入约为2030年预测终点的25.29%。",
        "counterevidence_zh": "预测终点不是当前可立即采购的剩余市场；医院预算、验收、责任和回款使收入兑现慢于技术采用。",
        "uses": ["market_size", "forecast", "capability_boundary"],
    },
    {
        "id": "I07",
        "source_channel": "web",
        "source_tier": "government_primary",
        "publisher": "中华人民共和国教育部",
        "date": "2026-04-10",
        "title": "教育部等五部门推进人工智能+教育",
        "url": "https://www.moe.gov.cn/fbh/live/2026/77927/mtbd/202604/t20260413_1433410.html",
        "independence_key": "moe_beijing_ai_education_coverage_2025",
        "independence_rationale": "教育部发布会转载北京市教委的学校覆盖率和政策事实。",
        "candidates": ["科大讯飞", "视源股份", "佳发教育"],
        "entity_key": "ai_application_subsectors",
        "metric": "教育AI部署覆盖与付费边界",
        "claim_zh": "截至2025年底，北京各类学校AI应用覆盖率达到87.7%，说明教学和管理场景已广泛触达。",
        "counterevidence_zh": "这是北京地区部署覆盖率，不是全国付费渗透率，也没有披露每校预算、AI增量合同或续费。",
        "uses": ["adoption", "conversion_boundary"],
    },
    {
        "id": "I08",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2025-11-01",
        "title": "China AI: Redefining Global Competition for the AI Era",
        "title_zh": "中国AI：重塑AI时代的全球竞争",
        "language": "en",
        "excerpt": "China AI coding product revenue was less than RMB100 million in 2025, while leading vendors were already reporting rapid usage growth.",
        "excerpt_zh": "2025年中国AI编程产品收入不足1亿元，但头部厂商使用量已经快速增长。",
        "url": "https://www.idc.com/wp-content/uploads/2025/11/IDC-Asia-Pacific-FutureScape-2026_China-AI-Excerpt.pdf",
        "independence_key": "idc_china_ai_coding_2025",
        "independence_rationale": "IDC中国AI Coding市场概览；使用量与收入属于同一份行业评估。",
        "candidates": ["阿里巴巴", "腾讯", "百度", "字节跳动"],
        "entity_key": "ai_application_subsectors",
        "metric": "AI编程产品收入与竞争阶段",
        "claim_zh": "中国AI编程已形成阿里Qoder、腾讯CodeBuddy、百度Comate、字节Trae等产品竞争，但2025年行业产品收入仍不足1亿元，商业化远落后于使用渗透。",
        "counterevidence_zh": "公开摘要没有统一席位数、续费率和企业收入，不能用代码生成占比直接估算供应商收入。",
        "uses": ["market_size", "competition", "conversion_boundary"],
    },
    {
        "id": "I09",
        "source_channel": "web",
        "source_tier": "government_primary",
        "publisher": "国家市场监督管理总局",
        "date": "2026-04-07",
        "title": "2025年我国广告产业收入突破2万亿元",
        "url": "https://www.samr.gov.cn/xw/zj/art/2026/art_c26cc939029e4faf86674ff7ac0c1ee5.html",
        "independence_key": "samr_china_advertising_2025",
        "independence_rationale": "市场监管总局发布的广告产业统计。",
        "candidates": ["蓝色光标", "万兴科技", "视觉中国", "快手"],
        "entity_key": "ai_application_subsectors",
        "metric": "广告与营销购买方支出池",
        "claim_zh": "2025年全国广告业务收入20502.1亿元，其中互联网广告13574.3亿元；这是AI创意和营销工具可能改造的购买方支出池，不是AI应用收入。",
        "counterevidence_zh": "不能拿AI公司收入除以全部广告收入得到产品渗透率，因为广告媒介费、代理费和软件费不是同一口径。",
        "uses": ["buyer_spend", "conversion_boundary"],
    },
    {
        "id": "I10",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-05-18",
        "title": "Token之外：中国私有化AI进入深水区",
        "url": "https://www.idc.com/resource-center/blog/token%E4%B9%8B%E5%A4%96%EF%BC%9A%E4%B8%AD%E5%9B%BD%E7%A7%81%E6%9C%89%E5%8C%96ai%E8%BF%9B%E5%85%A5%E6%B7%B1%E6%B0%B4%E5%8C%BA%EF%BC%8C%E5%B8%82%E5%9C%BA%E6%A0%BC%E5%B1%80%E8%BF%9C%E6%9C%AA%E5%AE%9A/",
        "independence_key": "idc_china_private_ai_software_2025",
        "independence_rationale": "IDC中国私有化AI软件市场跟踪。",
        "candidates": ["科大讯飞", "百度", "阿里巴巴", "腾讯", "第四范式"],
        "entity_key": "ai_application_subsectors",
        "metric": "私有化AI软件收入与竞争集中度",
        "claim_zh": "2025年中国私有化计算机视觉AI软件收入92.5亿元、语音语义AI软件118.6亿元，多数赛道CR3低于50%；语音语义前三家科大讯飞、百度和阿里合计40.2%。",
        "counterevidence_zh": "语音语义与视觉是基础能力口径，横跨办公、客服、医疗和教育，不能作为任一应用细分的收入分母。",
        "uses": ["market_size", "competition", "capability_layer"],
    },
    {
        "id": "I11",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-07-10",
        "title": "下一个超级办公入口，将由AI Agent定义",
        "url": "https://www.idc.com/resource-center/blog/%E4%B8%8B%E4%B8%80%E4%B8%AA%E8%B6%85%E7%BA%A7%E5%8A%9E%E5%85%AC%E5%85%A5%E5%8F%A3%EF%BC%8C%E5%B0%86%E7%94%B1ai-agent%E5%AE%9A%E4%B9%89-%E4%BD%86%E8%A7%84%E6%A8%A1%E5%8C%96%E8%90%BD/",
        "independence_key": "idc_china_intelligent_workplace_agents_2026",
        "independence_rationale": "IDC对中国智能化工作平台AI助手与Agent的产品评测和用户访谈。",
        "candidates": ["金山办公", "用友网络", "阿里巴巴", "腾讯"],
        "entity_key": "ai_application_subsectors",
        "metric": "办公智能体能力成熟度",
        "claim_zh": "办公AI已从内容辅助走向任务协同，但流程自动化、执行安全、权限治理和生态连接仍是整体低分项，规模化落地刚进入工程化阶段。",
        "counterevidence_zh": "产品评测没有给出付费席位、续费率或供应商收入，不能单独支撑估值上修。",
        "uses": ["capability_boundary", "market_stage"],
    },
    {
        "id": "I12",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2025-07-29",
        "title": "大模型赋能，智能客服2.0落地加速",
        "url": "https://www.idc.com/resource-center/blog/resource-region/3_328/page/34/",
        "independence_key": "idc_china_intelligent_customer_service_2024",
        "independence_rationale": "IDC中国智能客服市场份额研究公开摘要。",
        "candidates": ["百度", "阿里巴巴", "科大讯飞", "拓尔思"],
        "entity_key": "ai_application_subsectors",
        "metric": "智能客服产品阶段与竞争",
        "claim_zh": "大模型价格下降正在推动智能客服由问答、质检和坐席辅助向更复杂的营销、运营和决策场景扩展，行业已进入客服2.0产品迭代。",
        "counterevidence_zh": "公开摘要未给出市场规模和厂商份额，不能据此计算CR3或付费转化率。",
        "uses": ["market_stage", "competition"],
    },
    {
        "id": "I13",
        "source_channel": "web",
        "source_tier": "market_research_secondary",
        "publisher": "IDC",
        "date": "2026-06-15",
        "title": "中国AI专业服务市场进入结构性增长阶段",
        "url": "https://www.idc.com/resource-center/blog/%E4%B8%AD%E5%9B%BDai%E4%B8%93%E4%B8%9A%E6%9C%8D%E5%8A%A1%E5%B8%82%E5%9C%BA%E8%BF%9B%E5%85%A5%E7%BB%93%E6%9E%84%E6%80%A7%E5%A2%9E%E9%95%BF%E9%98%B6%E6%AE%B5%EF%BC%9A%E5%BA%94%E7%94%A8%E8%90%BD%E5%9C%B0/",
        "independence_key": "idc_china_ai_professional_services_2025",
        "independence_rationale": "IDC中国AI专业服务半年跟踪。",
        "candidates": ["软通动力", "用友网络", "鼎捷数智", "宝信软件"],
        "entity_key": "ai_application_subsectors",
        "metric": "AI专业服务与持续运营收入",
        "claim_zh": "2025年中国AI专业服务收入超过30亿美元，下半年接近20亿美元；增长正由基础设施集成转向平台应用和持续运营服务。",
        "counterevidence_zh": "该口径包含基础设施集成，不等于AI应用SaaS收入；项目制服务也可能提高收入而不改善毛利。",
        "uses": ["market_size", "business_model"],
    },
    {
        "id": "I14",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "福昕软件（新浪财经公告镜像）",
        "date": "2026-06-30",
        "title": "福昕软件2025年年度报告问询函回复",
        "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12419261&stockid=688095",
        "independence_key": "foxit_2025_annual_inquiry",
        "independence_rationale": "福昕软件对交易所问询的正式回复；公告镜像仅是载体。",
        "candidates": ["福昕软件"],
        "entity_key": "ai_application_companies",
        "metric": "办公文档公司订阅收入与ARR",
        "claim_zh": "福昕软件2025年软件产品授权收入9.10亿元，其中订阅收入同比增长59.03%并成为主要收入来源；核心业务ARR约5.86亿元。该增长首先证明订阅转型，尚不能全部归因于AI。",
        "counterevidence_zh": "公司未单列AI助手收入、AI付费渗透率和推理成本，不能把订阅增长全部计作AI商业化。",
        "uses": ["company_progress", "company_comparison"],
    },
    {
        "id": "I15",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "汉王科技（公告PDF镜像）",
        "date": "2026-03-28",
        "title": "汉王科技2025年年度报告",
        "url": "https://pdf.dfcfw.com/pdf/H2_AN202603271820814044_1.pdf",
        "independence_key": "hanwang_2025_annual",
        "independence_rationale": "汉王科技法定年报；东方财富仅为PDF载体。",
        "candidates": ["汉王科技"],
        "entity_key": "ai_application_companies",
        "metric": "办公文档公司AI终端收入",
        "claim_zh": "汉王科技2025年AI终端收入5.00亿元、同比增长19.23%，但毛利率35.76%、同比下降2.83个百分点；产品已形成收入，盈利质量尚未同步改善。",
        "counterevidence_zh": "AI终端包含硬件与多类功能，不能与文档SaaS或智能体收入直接比较。",
        "uses": ["company_progress", "financial_quality"],
    },
    {
        "id": "I16",
        "source_channel": "web",
        "source_tier": "company_filing_primary",
        "publisher": "宇信科技",
        "date": "2026-03-30",
        "title": "宇信科技2025年年度报告",
        "url": "https://disc.static.szse.cn/download/disc/disk03/finalpage/2026-03-30/27a8b789-547b-4642-a7a6-f3d7635b8988.pdf",
        "independence_key": "yusys_2025_annual",
        "independence_rationale": "深交所披露的宇信科技法定年报。",
        "candidates": ["宇信科技"],
        "entity_key": "ai_application_companies",
        "metric": "金融AI产品与项目阶段",
        "claim_zh": "宇信科技已发布AI手机银行V1.0并形成从业务设计、项目实施、监管报备到上线运营的链路；2025年还中标股份制银行AI算力和模型平台等项目，但多数客户未具名、AI收入未单列。",
        "counterevidence_zh": "产品发布和中标不能替代验收、收入确认、回款与续费；匿名客户项目也不能用于计算银行覆盖率。",
        "uses": ["company_progress", "contract_stage"],
    },
    {
        "id": "I17",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "奇安信（新浪财经公告镜像）",
        "date": "2026-04-30",
        "title": "奇安信2025年年度报告",
        "url": "https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12285369",
        "independence_key": "qianxin_2025_annual",
        "independence_rationale": "奇安信法定年报；新浪财经仅为公告载体。",
        "candidates": ["奇安信"],
        "entity_key": "ai_application_companies",
        "metric": "AI安全产品落地与财务质量",
        "claim_zh": "奇安信的AISOC、AI代码卫士和大模型卫士已在新能源、汽车、有色、金融、能源和运营商等行业形成项目，但2025年收入43.92亿元、归母净亏损12.87亿元，毛利率下降5.67个百分点。",
        "counterevidence_zh": "公司未单列上述AI产品收入；项目落地尚不足以证明它们已经覆盖高研发投入并形成可持续利润。",
        "uses": ["company_progress", "financial_quality"],
    },
    {
        "id": "I18",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "启明星辰（新浪财经公告镜像）",
        "date": "2026-04-13",
        "title": "启明星辰2025年年度报告摘要",
        "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12082073&stockid=002439",
        "independence_key": "venustech_2025_annual",
        "independence_rationale": "启明星辰法定年报摘要；公告镜像仅为载体。",
        "candidates": ["启明星辰"],
        "entity_key": "ai_application_companies",
        "metric": "AI安全订单与研发负担",
        "claim_zh": "启明星辰披露大模型应用防火墙、访问安全代理、评估、脱敏和安全运营等产品矩阵实现订单突破并有多行业实践；2025年研发投入占收入31.19%。",
        "counterevidence_zh": "公司没有披露AI订单金额、收入和毛利，‘订单突破’只能证明早期需求，不能证明规模盈利。",
        "uses": ["company_progress", "contract_stage"],
    },
    {
        "id": "I19",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "视源股份（新浪财经公告镜像）",
        "date": "2026-03-25",
        "title": "视源股份2025年年度报告",
        "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12015844&stockid=002841",
        "independence_key": "cvte_2025_annual",
        "independence_rationale": "视源股份法定年报；公告镜像仅为载体。",
        "candidates": ["视源股份"],
        "entity_key": "ai_application_companies",
        "metric": "教育AI产品和商业阶段",
        "claim_zh": "视源股份的学生作业智能批阅与学情一体机已投入市场应用，覆盖采集、批改、分析、讲评和个性化提升；公司未单列该产品收入、学校数量和续费。",
        "counterevidence_zh": "‘投入市场’不是批量付费证明，且软硬件收入、部署成本和AI增量价值尚未拆分。",
        "uses": ["company_progress", "product_stage"],
    },
    {
        "id": "I20",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "卫宁健康（新浪财经公告镜像）",
        "date": "2026-04-15",
        "title": "卫宁健康2025年年度报告",
        "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12089041&stockid=300253",
        "independence_key": "winning_health_2025_annual",
        "independence_rationale": "卫宁健康法定年报；公告镜像仅为载体。",
        "candidates": ["卫宁健康"],
        "entity_key": "ai_application_companies",
        "metric": "医疗AI产品与收入转化",
        "claim_zh": "卫宁健康持续把AI嵌入医疗软件和数字健康场景，但2025年WiNEX升级替换尚未转化为规模收入，说明产品投入与财务兑现仍有明显时滞。",
        "counterevidence_zh": "研究活动和产品规划不能替代AI增量合同、验收、医院回款和毛利。",
        "uses": ["company_progress", "conversion_boundary"],
    },
    {
        "id": "I21",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "创业慧康（公告PDF镜像）",
        "date": "2026-04-15",
        "title": "创业慧康2025年年度报告摘要",
        "url": "https://notice.10jqka.com.cn/api/pdf/2bfb2848bef73ffc.pdf",
        "independence_key": "bsoft_2025_annual",
        "independence_rationale": "创业慧康法定年报摘要；同花顺仅为PDF载体。",
        "candidates": ["创业慧康"],
        "entity_key": "ai_application_companies",
        "metric": "医疗信息化公司财务与AI转型",
        "claim_zh": "创业慧康2025年收入10.52亿元、同比下降26.07%，归母净亏损4.02亿元，经营现金流转负；公司推进AI医疗产品，但现有财务结果没有证明AI已抵消传统业务下滑。",
        "counterevidence_zh": "不能因行业长期空间大而忽略公司收入收缩、亏损和现金流恶化。",
        "uses": ["company_progress", "financial_quality"],
    },
    {
        "id": "I22",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "视觉中国（新浪财经公告镜像）",
        "date": "2026-03-31",
        "title": "视觉中国2025年年度报告",
        "url": "https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12047786&stockid=000681",
        "independence_key": "vcg_2025_annual",
        "independence_rationale": "视觉中国法定年报；公告镜像仅为载体。",
        "candidates": ["视觉中国"],
        "entity_key": "ai_application_companies",
        "metric": "AI内容收入与版权供给",
        "claim_zh": "视觉中国签约AI创作者超过1.2万人、收录AI辅助创作图片和视频超过900万件、累计销售超过5000万元；但2025年公司总收入下降4.03%、归母净利润下降30.31%。",
        "counterevidence_zh": "AI内容销售证明真实变现，但规模尚不足以抵消核心业务下滑，版权合规和平台竞争仍是约束。",
        "uses": ["company_progress", "financial_quality"],
    },
    {
        "id": "I23",
        "source_channel": "web",
        "source_tier": "company_primary",
        "publisher": "快手科技",
        "date": "2026-01-13",
        "title": "可灵AI年化收入运行率在2025年12月达2.4亿美元",
        "url": "https://ir.kuaishou.com/zh-hans/news-releases/news-release-details/kelingainianhuashouruyunxingluzai2025nian12yueda24yimeijin",
        "independence_key": "kuaishou_kling_arr_202512",
        "independence_rationale": "快手投资者关系发布的可灵AI月收入和年化运行率。",
        "candidates": ["快手"],
        "entity_key": "ai_application_companies",
        "metric": "生成式视频产品收入",
        "claim_zh": "可灵AI在2025年12月单月收入超过2000万美元，对应年化收入运行率2.4亿美元；这是创意应用中少数可核验的独立产品收入。",
        "counterevidence_zh": "年化运行率不是已确认年度收入，也没有披露获客成本、推理成本和独立利润。",
        "uses": ["company_progress", "business_model"],
    },
    {
        "id": "I24",
        "source_channel": "web",
        "source_tier": "company_primary",
        "publisher": "腾讯云",
        "date": "2025-07-01",
        "title": "CodeBuddy AI Coding企业场景落地实践",
        "url": "https://cloud.tencent.com/developer/article/2555275",
        "independence_key": "tencent_codebuddy_internal_adoption_2025",
        "independence_rationale": "腾讯云披露的内部使用与产品实践；效率数据由供应商自报。",
        "candidates": ["腾讯"],
        "entity_key": "ai_application_companies",
        "metric": "代码助手使用与效率",
        "claim_zh": "腾讯披露CodeBuddy覆盖5万多名内部开发者，编码时长缩短40%、AI代码生成占比超过43%；这证明高频使用价值，但不代表外部客户收入。",
        "counterevidence_zh": "供应商内部自报效率未经过独立审计，且内部采用不能替代外部席位、续费和毛利。",
        "uses": ["buyer_roi", "product_stage"],
    },
    {
        "id": "I25",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "蓝色光标（中国证券报转述）",
        "date": "2026-04-16",
        "title": "蓝色光标2025年AI驱动收入达37.25亿元",
        "url": "https://finance.eastmoney.com/a/202604153706325327.html",
        "independence_key": "bluefocus_2025_ai_driven_revenue",
        "independence_rationale": "蓝色光标年报数据的媒体转述；AI驱动口径沿用公司定义。",
        "candidates": ["蓝色光标"],
        "entity_key": "ai_application_companies",
        "metric": "AI营销驱动收入",
        "claim_zh": "蓝色光标2025年AI驱动收入37.25亿元、同比增长210.42%，占总收入5.42%；该口径证明AI已参与客户交付，但仍混合媒介采购、代理服务和技术能力。",
        "counterevidence_zh": "AI驱动收入不等于AI软件净收入，不能直接套用SaaS毛利率或估值倍数。",
        "uses": ["company_progress", "business_model"],
    },
    {
        "id": "I26",
        "source_channel": "web",
        "source_tier": "company_filing_primary",
        "publisher": "科大讯飞",
        "date": "2026-04-29",
        "title": "科大讯飞2025年年度报告：智慧教育业务",
        "url": "https://static.cninfo.com.cn/finalpage/2026-04-29/1225233581.PDF",
        "independence_key": "iflytek_2025_ar",
        "independence_rationale": "公司法定年报；与同一年度AI平台财务事实合并为一个发行人证据组。",
        "candidates": ["科大讯飞", "视源股份", "鸥玛软件"],
        "entity_key": "ai_application_companies",
        "metric": "教育AI部署、份额与付费模式",
        "claim_zh": "2025年科大讯飞智能批阅机已服务3000余所学校、公司披露市占率75%以上、日均批改作业超过360万份，并已形成财政经费设备采购、批改服务续费和数智化作业服务三种经费模式。",
        "counterevidence_zh": "市占率口径由公司披露，未给出行业分母、每校合同额、续费率、毛利和回款；规模部署不能直接外推利润。",
        "uses": ["market_position", "buyer_payment", "company_progress"],
    },
    {
        "id": "I27",
        "source_channel": "web",
        "source_tier": "company_primary",
        "publisher": "鸥玛软件",
        "date": "2026-05-20",
        "title": "鸥玛软件2025年度业绩说明会",
        "url": "https://irm.cninfo.com.cn/interview/interview/activityInfo?activityId=1448444984436457472",
        "independence_key": "ouma_2025_results_briefing_ai_contracts",
        "independence_rationale": "上市公司业绩说明会原始问答，可确认合同计价方式与具名采购方；金额仍属于混合考试服务合同。",
        "candidates": ["鸥玛软件"],
        "entity_key": "ai_application_companies",
        "metric": "教育考试AI合同与计费",
        "claim_zh": "鸥玛软件披露2025年AI技术服务已在部分考试服务项目中作为独立计价项，按服务量收费；公司另中标中国证券业协会2026—2028年计算机化考试服务项目5760万元。",
        "counterevidence_zh": "5760万元是完整考试服务合同，不是纯AI收入；公司没有拆出AI计价项金额、毛利和续约比例。",
        "uses": ["named_contract", "pricing_model", "commercialization_boundary"],
    },
    {
        "id": "I28",
        "source_channel": "web",
        "source_tier": "company_filing_primary",
        "publisher": "拓尔思",
        "date": "2026-04-15",
        "title": "拓尔思2025年年度报告摘要",
        "url": "https://static.cninfo.com.cn/finalpage/2026-04-15/1225103278.PDF",
        "independence_key": "trs_2025_ar",
        "independence_rationale": "公司法定披露，可确认细分收入与产品客户，不能替代合同明细。",
        "candidates": ["拓尔思"],
        "entity_key": "ai_application_companies",
        "metric": "企业搜索、客服与金融AI收入",
        "claim_zh": "拓尔思2025年金融科技收入7084万元，其中AI与数据类业务收入4753万元；公司同时披露政务问答、舆情、研报写作和企业知识服务等智能体产品及具名央企场景。",
        "counterevidence_zh": "该AI与数据口径混合数据产品和服务，不等于智能客服或单一Agent收入；需要续费、毛利和跨客户复制验证。",
        "uses": ["ai_revenue", "named_customer", "business_model"],
    },
    {
        "id": "I29",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "绿盟科技（公司公告镜像）",
        "date": "2026-04-23",
        "title": "绿盟科技2025年年度报告",
        "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12154056&stockid=300369",
        "independence_key": "nsfocus_2025_ar",
        "independence_rationale": "公司法定年报的公开镜像；AI产品、落地和财务均来自同一发行人证据组。",
        "candidates": ["绿盟科技"],
        "entity_key": "ai_application_companies",
        "metric": "AI安全产品与盈利修复",
        "claim_zh": "绿盟科技2025年推出覆盖模型训练、微调、部署和运营的AI安全服务与清风卫产品，并称在运营商、金融等行业落地；收入25.41亿元、归母净亏损0.45亿元、经营现金流2.16亿元。",
        "counterevidence_zh": "公司没有拆出AI安全合同和收入；整体减亏与现金流改善不能归因于AI产品。",
        "uses": ["company_progress", "financial_quality", "commercialization_boundary"],
    },
    {
        "id": "I30",
        "source_channel": "web",
        "source_tier": "company_filing_secondary_mirror",
        "publisher": "安恒信息（公司公告镜像）",
        "date": "2026-03-26",
        "title": "安恒信息2025年年度报告",
        "url": "https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12018515&stockid=688023",
        "independence_key": "dbappsecurity_2025_ar",
        "independence_rationale": "公司法定年报的公开镜像；客户部署和财务来自同一发行人。",
        "candidates": ["安恒信息"],
        "entity_key": "ai_application_companies",
        "metric": "AI安全客户部署与财务",
        "claim_zh": "安恒信息披露AI安服数字员工安小龙全年执行超过9000项任务、在40余家客户部署；2025年收入21.51亿元、归母净亏损0.58亿元，说明产品已有部署但尚未形成可拆分利润。",
        "counterevidence_zh": "任务数和客户数没有合同额、收费方式、续费与人工替代口径，不能用任务量直接估值。",
        "uses": ["customer_deployment", "financial_quality", "pricing_boundary"],
    },
    {
        "id": "I31",
        "source_channel": "web",
        "source_tier": "company_filing_primary",
        "publisher": "嘉和美康",
        "date": "2026-04-28",
        "title": "嘉和美康2025年年度报告",
        "url": "https://dataclouds.cninfo.com.cn/shgonggao/hsomarket/2026/20260428/9ef316ab613c486a9cd147d8f038ddeb.PDF",
        "independence_key": "goodwill_medical_2025_ar",
        "independence_rationale": "公司法定年报，直接讨论医疗大模型定价、产品与责任边界。",
        "candidates": ["嘉和美康"],
        "entity_key": "ai_application_companies",
        "metric": "医疗大模型定价阶段",
        "claim_zh": "嘉和美康在2025年年报中明确指出，医疗大模型的热度尚未带来定价模式、产品形态和方案价值的根本改变；当前竞争重点仍是医院数据中心、高质量数据集、专病库和临床工程能力。",
        "counterevidence_zh": "公司判断能够说明商业化边界，但不能据此推断其自身已经取得AI收入或市场份额。",
        "uses": ["pricing_boundary", "product_boundary", "counterevidence"],
    },
    {
        "id": "I32",
        "source_channel": "web",
        "source_tier": "company_filing_primary",
        "publisher": "软通动力",
        "date": "2026-04-25",
        "title": "软通动力2025年年度报告",
        "url": "https://static.cninfo.com.cn/finalpage/2026-04-25/1225192662.PDF",
        "independence_key": "isoftstone_2025_ar_ai_delivery",
        "independence_rationale": "公司法定年报，可确认内部开发工具、交付模式和客户范围，未披露量化效率与AI产品利润。",
        "candidates": ["软通动力"],
        "entity_key": "ai_application_companies",
        "metric": "AI编程购买方效率与服务模式",
        "claim_zh": "软通动力已在需求分析、编码、测试和交付中使用AISE、天璇和睿动AI平台，并尝试“人+Tokens”交付；同时为阿里、蚂蚁、字节等客户提供模型数据服务。",
        "counterevidence_zh": "公司只称效率显著提升，未披露节省工时、人员变化、项目毛利和客户价格；AI也可能压低按人天收费的传统收入。",
        "uses": ["buyer_roi", "business_model_transition", "company_progress"],
    },
    {
        "id": "I33",
        "source_channel": "web",
        "source_tier": "company_filing_primary",
        "publisher": "彩讯股份",
        "date": "2026-04-11",
        "title": "彩讯股份2025年年度报告",
        "url": "https://static.cninfo.com.cn/finalpage/2026-04-11/1225095921.PDF",
        "independence_key": "richinfo_2025_ar",
        "independence_rationale": "公司法定年报，可确认具名客户和业务分部；AI收入仍与原有渠道和智算业务混合。",
        "candidates": ["彩讯股份"],
        "entity_key": "ai_application_companies",
        "metric": "智能客服与协同办公客户",
        "claim_zh": "彩讯股份2025年收入18.30亿元、归母净利润2.91亿元、经营现金流4.63亿元；公司披露南方航空、中国人寿AI邮箱项目，并在运营商和能源场景推进智能外呼与智能消息。",
        "counterevidence_zh": "协同办公、智慧渠道、智算和数据业务混合，未单列AI邮箱或智能外呼合同额；收购项目的协同不能提前计入利润。",
        "uses": ["named_customer", "financial_quality", "commercialization_boundary"],
    },
    {
        "id": "I34",
        "source_channel": "report",
        "source_tier": "sell_side_secondary",
        "publisher": "UBS",
        "date": "2026-04-01",
        "title": "Yusys Technologies FY2025 results: a revenue dip with margin gains",
        "title_zh": "宇信科技2025年业绩：收入下降但利润率改善",
        "language": "en",
        "excerpt": "UBS cut FY2026-2028 EPS estimates and its price target to RMB26.30 after FY2025 results, while highlighting AI-native banking architecture and AI Agent deployment.",
        "excerpt_zh": "UBS在2025年业绩后下调宇信科技2026—2028年EPS预测并把目标价降至26.30元，同时关注AI原生银行架构和智能体部署。",
        "url": "https://r.datayes.com/",
        "local_path": "papers/AI应用/2026-04-01_UBS_宇信科技（300674）：First Read_n宇信科技_n2025财年业绩：收入下滑但利润率提升.pdf",
        "independence_key": "ubs_yusys_20260401",
        "independence_rationale": "UBS独立公司研究；仅作独立模型冻结后的外部对账，不与数据商一致预期重复计权。",
        "candidates": ["宇信科技"],
        "entity_key": "ai_application_companies",
        "metric": "宇信科技外部盈利与估值对账",
        "claim_zh": "UBS预测宇信科技2026—2028年EPS为0.76、0.93和1.13元，按33倍2026年PE给出26.30元目标价；报告认为利润率改善重要，但AI收入尚未单列。",
        "counterevidence_zh": "这是卖方预测而非事实，且目标价对PE倍数敏感；不能替代AI合同、验收和回款。",
        "uses": ["external_reconciliation", "valuation_boundary"],
    },
    {
        "id": "I35",
        "source_channel": "report",
        "source_tier": "sell_side_secondary",
        "publisher": "海通国际证券",
        "date": "2026-07-01",
        "title": "宇信科技：布局具身智能与AI，加速业务升维",
        "url": "https://r.datayes.com/",
        "local_path": "papers/AI应用/2026-07-01_海通国际证券_宇信科技（300674）：布局具身智能与AI，加速业务升维.pdf",
        "independence_key": "haitong_international_yusys_20260701",
        "independence_rationale": "海通国际独立公司研究；发布日期处于研究截止日前最近两个季度。",
        "candidates": ["宇信科技"],
        "entity_key": "ai_application_companies",
        "metric": "宇信科技近期机构预测",
        "claim_zh": "海通国际预测宇信科技2026—2028年归母净利润5.00、5.92和6.96亿元，按28倍2026年PE给出19.88元目标价。",
        "counterevidence_zh": "该估值明显低于UBS目标价，差异主要来自EPS和倍数；两份报告都不能证明AI是利润增长的主要来源。",
        "uses": ["external_reconciliation", "valuation_boundary"],
    },
    {
        "id": "I36",
        "source_channel": "report",
        "source_tier": "sell_side_secondary",
        "publisher": "HSBC Qianhai Securities",
        "date": "2026-07-13",
        "title": "CVTE: profitability poised to rise to a new level",
        "title_zh": "视源股份：盈利能力有望提升至新水平",
        "language": "en",
        "excerpt": "HSBC raised FY2026-2028 earnings estimates and its target price to RMB75.40, citing education AI and control-board margin improvement.",
        "excerpt_zh": "汇丰上调视源股份2026—2028年盈利预测和目标价至75.40元，理由包括教育AI与主控板利润率改善。",
        "url": "https://r.datayes.com/",
        "local_path": "papers/AI应用/2026-07-13_汇丰_视源股份（002841）：买入评级：盈利能力有望提升至新水平.pdf",
        "independence_key": "hsbc_cvte_20260713",
        "independence_rationale": "汇丰独立公司研究；AI教育与主控板改善必须分别解释，不能把全部上调归于AI。",
        "candidates": ["视源股份"],
        "entity_key": "ai_application_companies",
        "metric": "视源股份外部盈利与估值对账",
        "claim_zh": "汇丰预测视源股份2026—2028年EPS为2.94、3.50和3.97元，并给出75.40元目标价；报告同时把利润上调归因于教育AI、主控板传价和汽车电子。",
        "counterevidence_zh": "视源利润修复不是单一AI变量，若主控板毛利正常化，不能用教育AI叙事解释全部盈利上行。",
        "uses": ["external_reconciliation", "valuation_boundary"],
    },
    {
        "id": "I37",
        "source_channel": "report",
        "source_tier": "sell_side_secondary",
        "publisher": "华创证券",
        "date": "2026-07-25",
        "title": "视源股份2026年半年度业绩预告点评",
        "url": "https://r.datayes.com/",
        "local_path": "papers/AI应用/2026-07-25_华创证券_视源股份（002841）：2026半年度业绩预告点评：26H1业绩预告超预期，主业多点开花.pdf",
        "independence_key": "huachuang_cvte_20260725",
        "independence_rationale": "华创证券独立公司研究；发布日期处于研究截止日前最近两个季度。",
        "candidates": ["视源股份"],
        "entity_key": "ai_application_companies",
        "metric": "视源股份近期机构预测",
        "claim_zh": "华创预测视源股份2026—2028年归母净利润23.98、27.02和30.05亿元，DCF目标价60元；AI教育软件付费是增长因素之一。",
        "counterevidence_zh": "目标价低于汇丰且方法不同，表明上沿对利润率和终值敏感；AI教育合同收入仍未单列。",
        "uses": ["external_reconciliation", "valuation_boundary"],
    },
    {
        "id": "I38",
        "source_channel": "report",
        "source_tier": "sell_side_secondary",
        "publisher": "华泰证券",
        "date": "2026-05-04",
        "title": "奇安信：2026年盈利修复节奏有望加快",
        "url": "https://r.datayes.com/",
        "local_path": "papers/AI应用/2026-05-04_华泰证券_奇安信（688561）：2026年盈利修复节奏有望加快.pdf",
        "independence_key": "huatai_qianxin_20260504",
        "independence_rationale": "华泰证券独立公司研究；用作亏损路径和估值方法对账。",
        "candidates": ["奇安信"],
        "entity_key": "ai_application_companies",
        "metric": "奇安信近期盈利预测",
        "claim_zh": "华泰预测奇安信2026、2027年仍亏损7.38亿元和3.34亿元，2028年才盈利1.68亿元，并采用6倍2026年PS给出42.60元目标价。",
        "counterevidence_zh": "PS估值绕开亏损但不能绕开现金流和毛利下降；AI产品放量尚未有独立收入证明。",
        "uses": ["external_reconciliation", "loss_path", "valuation_boundary"],
    },
    {
        "id": "I39",
        "source_channel": "report",
        "source_tier": "sell_side_secondary",
        "publisher": "华泰证券",
        "date": "2026-04-25",
        "title": "东方财富：高景气驱动经纪与代销双增",
        "url": "https://r.datayes.com/",
        "local_path": "papers/AI应用/2026-04-25_华泰证券_东方财富（300059）：高景气驱动经纪与代销双增.pdf",
        "independence_key": "huatai_eastmoney_20260425",
        "independence_rationale": "华泰证券独立公司研究；明确将盈利上调主要归因于经纪和代销，而非AI。",
        "candidates": ["东方财富"],
        "entity_key": "ai_application_companies",
        "metric": "东方财富近期盈利预测与AI归因",
        "claim_zh": "华泰预测东方财富2026—2028年归母净利润145.16、163.00和180.43亿元，目标价32.20元；同期公司推出资讯搜索、金融数据和智能选股三项AI技能。",
        "counterevidence_zh": "报告明确盈利上调主要来自经纪与基金代销高景气；不能把目标价或利润增长归因于AI技能。",
        "uses": ["external_reconciliation", "ai_attribution_boundary"],
    },
)


SUBSECTOR_RESEARCH: tuple[dict[str, Any], ...] = (
    {
        "name": "企业管理软件与工业流程",
        "score": 4.25,
        "market": "2025年中国AI增强ERP收入3.157亿美元、同比增长96.1%；另有超过30亿美元AI专业服务市场，但其中含基础设施集成，不能相加。",
        "stage": "从PoC进入模块采购和项目交付，真正稀缺的是把智能体接入财务、供应链、生产和审批权限后稳定执行。",
        "providers": "用友网络、金蝶国际、鼎捷数智、宝信软件、广联达；国际对照SAP、Oracle、Microsoft。",
        "buyers": "大型国企、制造业、建筑与钢铁客户按模块、项目、席位或持续运营付费。用友披露16.7亿元AI相关合同，鼎捷披露近2亿元AI签约，宝信和广联达已有具名行业案例。",
        "buyer_case": "付款已越过试点：用友2025年AI相关签约16.7亿元、鼎捷近2亿元、广联达2025年上半年AI直接合同超过0.40亿元。三者口径不同，不能相加；投资上分别要看实施亏损、验收转收入和高毛利增购。",
        "competition": "传统ERP/工业软件入口和实施能力构成壁垒；云厂商强在模型与平台，垂直厂商强在流程语义和客户数据。公开资料不足以计算同口径CR3。",
        "capability": "当前能做知识问答、报告、预测和局部流程；下一阶段是跨模块执行、权限审计和持续运营。若实施人效不提升，收入增长会被交付成本吃掉。",
        "investment": "行业质量居首、产业层面看多；股票优先鼎捷。用友仍亏损，宝信与广联达未拆出AI增量模块，三者当前均不按AI高增长给予额外估值。",
        "refs": ("app-i03", "app-i13", "app-c09", "app-c13", "app-c19", "app-c20"),
    },
    {
        "name": "网络安全与IT运营",
        "score": 4.15,
        "market": "2025年中国大模型安全运营平台收入15亿元、同比增长144%；相邻的ZTNA和SASE是更大安全预算池，但不是同一产品口径。",
        "stage": "安全运营已从告警总结走向调查、处置建议和部分自动响应；责任持续、数据私有和误报成本使客户更愿意付费。",
        "providers": "深信服、奇安信、启明星辰、绿盟科技、安恒信息；云平台的阿里、腾讯以及360也参与竞争。",
        "buyers": "政府、金融、运营商、制造、能源和关基客户购买平台、私有化部署和持续运营。深信服披露合同审查与安全运营效率案例，奇安信和启明星辰已形成跨行业项目。",
        "buyer_case": "深信服匿名制造客户把单份合同审查由5小时降至5分钟；安恒的AI安全数字员工在40余家客户执行超过9000项任务。两者都没有公开成交价，因此只能证明客户价值和部署，不能证明单位经济性。",
        "competition": "IDC公开摘要列出主要厂商但未给份额，不能算CR3。真正壁垒是安全数据、处置工作流、责任承担和持续服务，而不是接入同一个开源模型。",
        "capability": "当前擅长告警归并、研判、代码与模型安全检查；未来边界取决于自动处置权限、可审计性和误杀责任。高风险动作仍需人在环。",
        "investment": "行业层面看多，股票层面谨慎：深信服估值已要求利润率修复；奇安信和启明星辰尚未披露AI收入且研发负担高，当前均不进入应用核心组合。",
        "refs": ("app-i05", "app-c11", "app-c25", "app-i17", "app-i18"),
    },
    {
        "name": "办公、文档与企业知识",
        "score": 4.05,
        "market": "权威机构尚未公开同口径中国办公AI收入。可核验的公司收入包括WPS 365的7.20亿元和福昕核心业务ARR 5.86亿元，但两者都混合传统订阅，不能相加成行业AI市场。",
        "stage": "总结、翻译、写作和检索已成熟；企业级Agent正在进入任务协同，但权限、流程执行安全和生态连接仍是低成熟度环节。",
        "providers": "金山办公、合合信息、福昕软件、汉王科技；国际对照Microsoft 365、Google Workspace和Adobe。",
        "buyers": "个人按订阅付费，企业按席位、授权、API和私有化项目付费。WPS有公开席位价，合合有超过1000家企业客户及具名案例，福昕订阅转型已兑现ARR。",
        "buyer_case": "WPS 365公开企业席位价为199/399/599元/年，合合披露建信信托、东方希望和泰格医药等部署，福昕核心ARR约5.86亿元。公开标价、案例与ARR分别证明价格、场景和订阅基盘，但都没有直接给出AI增量收入。",
        "competition": "通用办公入口高度集中，文档识别、PDF和企业知识库仍有垂直空间；模型能力趋同后，文档格式、客户数据、分发入口和合规决定胜负。",
        "capability": "短期从内容生成走向检索、审批和跨文档任务；三年上限取决于能否安全执行跨系统流程，而不只是更好的聊天窗口。",
        "investment": "行业商业化质量较高；个股必须再过现金流和当前价格门槛。合合信息的付费与估值相对匹配，金山办公产品质量高但价格已高于独立核心区间；福昕和汉王尚未证明AI提高ARR、ARPU或毛利。",
        "refs": ("app-i11", "app-c01", "app-c03", "app-i14", "app-i15"),
    },
    {
        "name": "金融知识、投研与金融IT",
        "score": 3.90,
        "market": "中国金融生成式AI平台及应用由2024年9.14亿元预计增至2027年35.09亿元；2024年只相当于预测终点26.05%，但不能解释成当年74%市场待转化。",
        "stage": "知识问答、研报检索、投顾辅助、客服与代码开发已落地；信贷审批、交易和核心账户操作仍受合规、可解释和责任约束。",
        "providers": "同花顺、恒生电子、宇信科技、东方财富、指南针；云平台和大型金融机构也会自建。",
        "buyers": "个人为行情和投顾增值服务付费，券商、银行、基金为数据、平台、实施和维护付费。恒生披露20多家机构上线投顾智能体，宇信中标银行AI平台并推出AI手机银行。",
        "buyer_case": "恒生有20多家机构上线投顾智能体，宇信已有银行AI平台和AI手机银行项目；但上线机构数和项目中标均未披露AI客单价。东方财富和同花顺的利润又受成交活跃度影响，必须把AI提价与牛市流量分开。",
        "competition": "数据牌照、金融语料、客户连接和监管经验形成壁垒；但同花顺与东方财富盈利也高度受成交活跃度影响，不能把牛市收入算作AI。",
        "capability": "短期擅长检索、摘要、营销与辅助决策；能否进入信贷、交易和账户动作取决于审计、模型风险和人工复核。",
        "investment": "行业列第二梯队；同花顺质量高但价格已透支基准盈利，恒生和宇信尚未披露AI收费与续费，东方财富AI未单列收入，四者当前均不按纯AI溢价配置。",
        "refs": ("app-i04", "app-c05", "app-c18", "app-i16"),
    },
    {
        "name": "医疗AI与医疗信息化",
        "score": 3.75,
        "market": "2025年中国AI医疗应用软件收入35.4亿元，IDC预计2030年140亿元、渗透率44.7%；2025收入约为2030预测终点25.29%。",
        "stage": "病历生成、质控、导诊、影像和专病辅助正在采购；从‘给建议’到自动下医嘱、诊断和支付仍受临床责任与监管限制。",
        "providers": "科大讯飞及讯飞医疗、卫宁健康、东软集团、创业慧康、嘉和美康；医院和互联网医疗平台也自建。",
        "buyers": "医院、区域卫健部门和医保相关机构按软件、项目和运维付费。购买价值来自医生文书时间、编码质控和流程效率，但公开成交价、续费和分成普遍不足。",
        "buyer_case": "医疗IT公司普遍披露病历、质控、导诊和专病产品，却很少披露AI增量合同。嘉和美康甚至明确指出2025年尚未形成新的定价模式；因此医院需求是真实的，但付款、责任与回款尚未标准化。",
        "competition": "医院核心系统入口、专病数据、临床验证和合规是壁垒；模型准确率提高并不会自动替换HIS/EMR厂商。",
        "capability": "标准任务准确率接近可用后，未来价值转向长流程智能体；高风险诊疗必须可追溯、可复核并保留医生责任。",
        "investment": "行业长期看多、未来12个月谨慎。科大讯飞有平台收入和渠道但现金流不足；卫宁和创业慧康尚未把升级产品转成规模收入与回款，当前不进入核心组合。",
        "refs": ("app-i06", "app-c07", "app-i20", "app-i21"),
    },
    {
        "name": "创意内容与营销",
        "score": 3.55,
        "market": "2025年中国广告业务收入20502.1亿元、互联网广告13574.3亿元，这是购买方支出池而非AI软件TAM。可核验产品包括可灵AI年化收入运行率2.4亿美元、视觉中国AI内容累计销售5000万元。",
        "stage": "图像、视频和文案生成已完成产品化并开始付费；营销投放、素材生成和归因正在合并，但低切换成本和模型降价压缩独立工具价值。",
        "providers": "万兴科技、快手可灵、蓝色光标、视觉中国；国际对照Adobe、Canva、Runway。",
        "buyers": "创作者按订阅或点数付费，品牌和广告主按项目、媒介和效果付费。蓝色光标披露AI驱动收入37.25亿元，但该口径混合营销交付，不能套SaaS估值。",
        "buyer_case": "可灵AI单月收入超过2000万美元，视觉中国AI内容累计销售超过5000万元，万兴AI原生应用收入超过1.30亿元；蓝色光标37.25亿元则是混合营销交付。产品订阅、内容交易和代理总额法必须分别估值。",
        "competition": "基础模型、创作工具、版权内容库和营销渠道分层竞争。产品爆发快，但模型能力可替代；版权、分发、客户预算和效果归因才形成持续壁垒。",
        "capability": "当前能生成单项素材；未来是从brief、创作、投放到复盘的闭环。若平台把能力免费打包，独立工具必须依靠工作流、版权或渠道守住ARPU。",
        "investment": "可灵已证明全球C端付费，但A股相关公司中万兴仍亏损、蓝色光标低毛利媒介采购占主导、视觉中国AI销售额尚小；当前不设核心仓位。",
        "refs": ("app-i09", "app-i22", "app-i23", "app-c33", "app-i25"),
    },
    {
        "name": "智能客服、企业搜索与电商运营",
        "score": 3.45,
        "market": "权威公开资料没有给出同口径2025年市场规模。IDC确认客服2.0落地加速；137.3亿元公有云AI应用大盘包含客服和知识管理，但不能拆分。",
        "stage": "问答、质检、坐席辅助和外呼已成熟；下一阶段是跨订单、退款、营销和CRM执行，错误成本和权限边界明显上升。",
        "providers": "百度智能云、阿里云、腾讯云、科大讯飞、拓尔思；垂直联络中心厂商与大型平台自建并存。",
        "buyers": "运营商、金融、电商、汽车和政企热线按并发、调用、席位或项目付费。阿里公开外呼机器人频次可达人工4—5倍，但产品价格和客户侧净节省仍需逐案核验。",
        "buyer_case": "拓尔思披露金融科技中的AI与数据收入4753万元；彩讯披露南方航空、中国人寿AI邮箱项目。两者比单纯产品发布更接近付费，但仍需拆出续费、项目毛利和AI独立合同额。",
        "competition": "云厂商有模型、通信和渠道，垂直厂商有行业知识库与交付；基础问答容易被打包，复杂流程、历史数据和系统连接决定复购。",
        "capability": "低风险FAQ可高度自动化；退款、理赔、信贷和投诉升级需要身份、授权、审计和人工兜底。未来空间取决于从回答问题转向完成交易。",
        "investment": "行业ROI明确但A股纯度低；拓尔思、科大讯飞均未形成足以影响集团估值的独立收入和续费证据，当前不配置概念溢价，真正收入更多沉在云平台。",
        "refs": ("app-i02", "app-i12", "app-i10"),
    },
    {
        "name": "AI编程与软件开发",
        "score": 3.30,
        "market": "IDC公开资料显示2025年中国AI编程产品收入不足1亿元，远小于使用价值和全球市场；这是当前‘高采用、低变现’最明显的细分。",
        "stage": "补全、问答和局部代码生成已普及，项目级理解、测试、调试和多智能体执行仍是主要短板。",
        "providers": "阿里Qoder、腾讯CodeBuddy、百度Comate、字节Trae；国际对照GitHub Copilot、Cursor、Anthropic和Google。",
        "buyers": "个人开发者按月订阅，企业按席位、专有云和用量付费。腾讯内部5万多名开发者使用、AI代码占比超43%，说明效率价值高；但外部收入和续费没有同等披露。",
        "buyer_case": "腾讯内部5万多名开发者使用CodeBuddy并称编码时间缩短40%；软通动力把AI用于需求、编码、测试和交付并尝试“人+Tokens”。前者没有外部收入，后者没有量化毛利，因此当前更像购买方效率机会，而非成熟软件收入。",
        "competition": "模型和IDE入口快速迭代，价格低且多家平台补贴。企业代码库、评测、治理和部署连接能形成壁垒，但A股缺少高纯度上市标的。",
        "capability": "当前能加速编码，未来目标是完成需求到上线；项目上下文、可靠性、测试责任和安全限制决定Agent能否替代更多工时。",
        "investment": "行业潜力高但当前不可作为A股核心配置：供应商多属于大型互联网集团，产品收入不足以影响集团估值；软通动力更可能受益于交付效率，而非形成高毛利产品收入。",
        "refs": ("app-i08", "app-i24"),
    },
    {
        "name": "教育AI",
        "score": 3.65,
        "market": "公开资料没有全国同口径教育AI付费收入，但已出现产品级规模和独立计价：科大智能批阅机进入3000余所学校，鸥玛部分考试合同把AI服务单独计价。北京87.7%覆盖率仍只能说明触达。",
        "stage": "备课、批改、口语、学情和校务已规模试点，形成软硬一体产品；支付方、年度预算、硬件更新和回款决定商业化速度。",
        "providers": "科大讯飞、视源股份、鸥玛软件、拓维信息；非上市对照学而思、作业帮等。",
        "buyers": "学校、教育局、教师和家庭分别付费，经济机制不同。科大讯飞智能批阅机已进入3000余所学校并形成设备采购、批改续费和数智化作业服务三类付款；视源一体机已投放但收入未单列。",
        "buyer_case": "科大讯飞披露智能批阅机日均批改超过360万份和75%以上市占率；鸥玛软件已把AI技术服务列为合同独立计价项，并按服务量收费。前者规模强但单校收入不明，后者计价清楚但AI金额未拆。",
        "competition": "渠道、硬件入口、题库和区域数据构成壁垒；免费公共平台和通用模型会压低纯软件价格，厂商需证明学习结果而非仅节省备课时间。",
        "capability": "当前适合辅助和反馈；高风险评价、升学决策和未成年人数据使用仍需治理。未来边界取决于因材施教效果和可验证的教育结果。",
        "investment": "教育AI已进入付费模式验证，但当前只给中性行业判断：科大讯飞与鸥玛的证据最强，科大单校收入、续费和毛利仍缺；视源与拓维的AI收入归因更弱，不给予AI高估值溢价。",
        "refs": ("app-i07", "app-c07", "app-i26", "app-i27", "app-i19"),
    },
)


APPLICATION_COMPANY_EXTENSION_RESEARCH: tuple[dict[str, Any], ...] = (
    {
        "subsector": "办公、文档与企业知识",
        "company": "福昕软件",
        "ticker": "688095.SH",
        "role": "PDF与文档工作流提供方",
        "evidence": "2025年软件授权收入9.10亿元，订阅收入增长59.03%，核心业务ARR约5.86亿元；订阅转型已经验证，但AI助手收入、AI付费率和推理成本没有单列。",
        "financial_test": "先检验AI能否提高订阅ARPU、续费和核心ARR，而不是把全部订阅增长归为AI。没有AI收入拆分前，只能把AI视为留存和提价的可选上行。",
        "action": "产品入口真实、财务口径仍混合；待AI套餐、付费渗透或客户扩单可核验后再进入独立估值。",
        "refs": ("app-i14",),
    },
    {
        "subsector": "办公、文档与企业知识",
        "company": "汉王科技",
        "ticker": "002362.SZ",
        "role": "识别技术与AI终端提供方",
        "evidence": "2025年AI终端收入5.00亿元、增长19.23%，但该业务毛利率35.76%、下降2.83个百分点，说明产品收入增长没有同步改善盈利质量。",
        "financial_test": "必须拆出硬件销量、ASP、模型或软件收入、渠道成本和毛利；不能按SaaS倍数估值一个软硬混合终端业务。",
        "action": "有收入但毛利承压，当前优先级低于金山、合合与福昕；只有软件和订阅占比提高才上调。",
        "refs": ("app-i15",),
    },
    {
        "subsector": "金融知识、投研与金融IT",
        "company": "宇信科技",
        "ticker": "300674.SZ",
        "role": "银行IT与AI解决方案提供方",
        "evidence": "公司已推出AI手机银行V1.0，并披露银行AI算力、模型平台和境外数字货币项目；项目有中标、实施和投产阶段，但客户多匿名且AI收入未单列。",
        "financial_test": "近期两家机构预测差异明显：UBS给出2026—2028年EPS 0.76/0.93/1.13元和26.30元目标价，海通国际预测归母净利润5.00/5.92/6.96亿元并给出19.88元目标价。差异说明估值上限主要取决于利润率和倍数，不是产品发布。",
        "action": "银行客户入口强、AI归因弱；先看具名银行、合同金额、验收回款和AI模块毛利，再判断是否具备高于传统银行IT的倍数。",
        "refs": ("app-i16", "app-i34", "app-i35"),
    },
    {
        "subsector": "金融知识、投研与金融IT",
        "company": "东方财富",
        "ticker": "300059.SZ",
        "role": "金融流量、数据与交易平台",
        "evidence": "公司推出资讯搜索、金融数据和智能选股三项AI技能，但没有披露独立AI收入、套餐提价或付费转化。",
        "financial_test": "华泰预测2026—2028年归母净利润145.16/163.00/180.43亿元并给出32.20元目标价，盈利上调主要来自经纪与基金代销高景气；AI不能替代资本市场周期归因。",
        "action": "平台质量高，但本轮只能按证券流量与代销公司估值；AI只有在提高ARPU、留存或机构数据收入后才进入上行情景。",
        "refs": ("app-i39",),
    },
    {
        "subsector": "网络安全与IT运营",
        "company": "奇安信",
        "ticker": "688561.SH",
        "role": "安全运营与AI安全提供方",
        "evidence": "AISOC、AI代码卫士和大模型卫士已形成多行业项目，但2025年收入43.92亿元、归母净亏损12.87亿元，毛利率下降5.67个百分点。",
        "financial_test": "华泰仍预测2026、2027年亏损7.38亿元和3.34亿元，2028年才盈利1.68亿元，并采用6倍PS。AI若不能提高毛利和降低研发交付成本，收入增长不会形成股东回报。",
        "action": "产品覆盖广、财务修复最难；只有AI合同额、续费、毛利和经营现金流同时改善后才进入精确权重。",
        "refs": ("app-i17", "app-i38"),
    },
    {
        "subsector": "网络安全与IT运营",
        "company": "启明星辰",
        "ticker": "002439.SZ",
        "role": "安全产品与运营服务提供方",
        "evidence": "公司披露大模型防火墙、访问安全代理、评估、脱敏和安全运营产品出现订单突破，但未给金额；2025年研发投入占收入31.19%。",
        "financial_test": "需要AI订单转收入、毛利和中移动渠道协同形成可复核桥；高研发率意味着产品标准化不成功时，订单增长可能仍被费用吸收。",
        "action": "作为行业渠道型候选保留，未披露AI金额前不因‘订单突破’上修利润。",
        "refs": ("app-i18",),
    },
    {
        "subsector": "网络安全与IT运营",
        "company": "绿盟科技",
        "ticker": "300369.SZ",
        "role": "AI全生命周期安全提供方",
        "evidence": "2025年推出AI安全测评、备案与清风卫产品，并披露在运营商、金融落地；全年收入25.41亿元、归母净亏损0.45亿元、经营现金流2.16亿元。",
        "financial_test": "现金流转正优于仍大额亏损的同业，但AI收入没有拆出；应验证项目复用率、收入确认、毛利和回款，而非把整体减亏归因于AI。",
        "action": "财务修复领先奇安信，但商业纯度仍不足；可列安全组第二梯队观察，尚不提高组合权重。",
        "refs": ("app-i29",),
    },
    {
        "subsector": "网络安全与IT运营",
        "company": "安恒信息",
        "ticker": "688023.SH",
        "role": "数据安全与AI安全运营提供方",
        "evidence": "安小龙全年执行超过9000项任务并在40余家客户部署；2025年收入21.51亿元、归母净亏损0.58亿元。",
        "financial_test": "任务量必须还原为每客户收费、续费、人工替代和毛利。40家部署若主要是试点或随传统合同赠送，不能支撑独立估值溢价。",
        "action": "客户触达已验证、收费仍未验证；优先补单客收入与续费，再与深信服、绿盟比较。",
        "refs": ("app-i30",),
    },
    {
        "subsector": "医疗AI与医疗信息化",
        "company": "科大讯飞",
        "ticker": "002230.SZ",
        "role": "医疗大模型、语音语义与行业平台提供方",
        "evidence": "公司2025年AI平台收入12.52亿元、MaaS/API收入3.85亿元，但医疗AI没有单列收入；行业规模和公司平台收入不能直接相减。",
        "financial_test": "医疗业务必须按医院或区域项目的合同、验收、回款和毛利单独拆分。公司整体高研发和资本开支意味着医疗应用增长只有转成自由现金流才有估值意义。",
        "action": "平台和渠道领先，医疗收入纯度不足；保留行业龙头地位，但不把医疗AI远期市场全部计入基准利润。",
        "refs": ("app-i06", "app-c07"),
    },
    {
        "subsector": "医疗AI与医疗信息化",
        "company": "卫宁健康",
        "ticker": "300253.SZ",
        "role": "医院核心系统与AI升级提供方",
        "evidence": "公司持续把AI嵌入医疗软件和数字健康场景，但2025年WiNEX替换尚未转化为规模收入。",
        "financial_test": "医院核心系统入口有交叉销售价值，但先要看到新一代产品验收、医院回款、实施毛利和AI增购；不能拿行业140亿元远期空间直接分配公司份额。",
        "action": "入口有价值、兑现落后；在产品收入和回款改善前只作医疗IT观察候选。",
        "refs": ("app-i20",),
    },
    {
        "subsector": "医疗AI与医疗信息化",
        "company": "创业慧康",
        "ticker": "300451.SZ",
        "role": "区域医疗与医院信息化提供方",
        "evidence": "2025年收入10.52亿元、下降26.07%，归母净亏损4.02亿元且经营现金流转负；AI产品尚未抵消存量业务下滑。",
        "financial_test": "基准情景必须先修复基础收入、项目验收和现金流，再讨论AI利润；长期行业增长无法补偿短期财务失速。",
        "action": "当前不进入估值候选，直到收入止跌、现金流转正且AI合同可拆分。",
        "refs": ("app-i21",),
    },
    {
        "subsector": "医疗AI与医疗信息化",
        "company": "嘉和美康",
        "ticker": "688246.SH",
        "role": "电子病历、临床数据与专病平台提供方",
        "evidence": "公司自身判断2025年医疗大模型尚未改变定价模式和产品形态，竞争重点仍是医院数据中心、高质量数据集和专病库。",
        "financial_test": "这意味着AI短期更像项目能力和产品防守，而非独立订阅曲线；只有新增模块价格、客户扩单和实施人效披露后才能进财务模型。",
        "action": "产业位置可研究，商业化证据不足；不因医疗AI热度提前上修估值。",
        "refs": ("app-i31",),
    },
    {
        "subsector": "创意内容与营销",
        "company": "蓝色光标",
        "ticker": "300058.SZ",
        "role": "营销服务与生成式内容交付方",
        "evidence": "2025年AI驱动收入37.25亿元、增长210.42%，占总收入5.42%；口径证明AI进入交付，但混合媒介采购、代理和技术服务。",
        "financial_test": "必须从总额法收入中拆出净收入、毛利、客户留存和应收；37亿元不能按软件收入估值，真正变量是AI是否降低创意人力和提高项目毛利。",
        "action": "规模证据强、利润纯度弱；关注AI驱动毛利而不是AI驱动收入。",
        "refs": ("app-i25",),
    },
    {
        "subsector": "创意内容与营销",
        "company": "视觉中国",
        "ticker": "000681.SZ",
        "role": "版权内容库与AI内容交易平台",
        "evidence": "签约AI创作者超过1.2万人、AI辅助内容超过900万件、累计销售超过5000万元；同期总收入下降4.03%、净利润下降30.31%。",
        "financial_test": "AI销售是真实收入，但相对公司基数仍小。核心检验是版权合规、单位内容销售、平台分成和AI内容是否带来净新增而非替代传统图库。",
        "action": "有付费闭环但规模不足，适合作为版权壁垒观察标的，不因素材数量上修终值。",
        "refs": ("app-i22",),
    },
    {
        "subsector": "创意内容与营销",
        "company": "快手",
        "ticker": "01024.HK",
        "role": "生成式视频产品和内容平台",
        "evidence": "可灵AI在2025年12月单月收入超过2000万美元，对应年化运行率2.4亿美元，是少数独立披露产品收入的创意AI。",
        "financial_test": "仍需扣除模型推理、渠道补贴和获客成本，并验证月度收入是否持续；年化运行率不能替代全年利润。",
        "action": "创意组商业证据最强，但对快手集团估值的影响取决于收入持续和独立利润率。",
        "refs": ("app-i23",),
    },
    {
        "subsector": "智能客服、企业搜索与电商运营",
        "company": "拓尔思",
        "ticker": "300229.SZ",
        "role": "企业搜索、知识库与行业智能体提供方",
        "evidence": "2025年金融科技收入7084万元，其中AI与数据类4753万元；产品进入政务问答、舆情、研报写作和央企知识场景。",
        "financial_test": "4753万元仍混合数据业务，需拆出订阅、项目与续费。若收入主要依赖定制交付，模型和开源检索能力降价会压缩毛利。",
        "action": "A股纯度高于云平台但规模小；只有AI收入连续增长且毛利稳定才进入组合。",
        "refs": ("app-i28",),
    },
    {
        "subsector": "智能客服、企业搜索与电商运营",
        "company": "彩讯股份",
        "ticker": "300634.SZ",
        "role": "运营商渠道、智能外呼与协同办公提供方",
        "evidence": "2025年收入18.30亿元、净利润2.91亿元、经营现金流4.63亿元，并披露南方航空、中国人寿AI邮箱及运营商、能源智能外呼场景。",
        "financial_test": "财务质量优于多数项目制应用公司，但AI合同额未拆出。需要判断AI邮箱和外呼是新增收费、存量续约防守还是收购带来的收入。",
        "action": "可作为客服与办公组财务质量候选，补齐AI收入和单客价值后再与拓尔思比较。",
        "refs": ("app-i33",),
    },
    {
        "subsector": "智能客服、企业搜索与电商运营",
        "company": "百度",
        "ticker": "09888.HK",
        "role": "公有云AI应用和智能客服平台",
        "evidence": "IDC披露百度智能云在2025年中国公有云AI应用服务口径份额30.7%，该口径含客服、知识管理和内容创作。",
        "financial_test": "份额不能拆成客服收入，也没有公开产品级利润；评估集团时还要扣除模型、算力和云基础设施投入。",
        "action": "行业龙头对照而非纯应用标的；除非产品收入和利润被单列，不把30.7%份额直接映射估值。",
        "refs": ("app-i02",),
    },
    {
        "subsector": "智能客服、企业搜索与电商运营",
        "company": "阿里巴巴",
        "ticker": "09988.HK",
        "role": "云平台、电商运营与客服智能体提供方",
        "evidence": "公司在云、店铺运营和客服工作流有分发入口，但公开行业口径没有拆出智能客服合同、续费和独立利润。",
        "financial_test": "应按云收入、模型调用和电商增值服务分别建模；不能把平台内部效率和商家使用量全部记为软件收入。",
        "action": "战略能力强、集团归因弱；作为竞争格局和价格基准，不以客服概念单独加权。",
        "refs": ("app-i02", "app-i12"),
    },
    {
        "subsector": "AI编程与软件开发",
        "company": "腾讯控股",
        "ticker": "00700.HK",
        "role": "CodeBuddy产品提供方和内部购买方",
        "evidence": "CodeBuddy覆盖腾讯内部5万多名开发者，编码时间缩短40%、AI代码占比超过43%；使用价值明确，外部席位和收入未披露。",
        "financial_test": "对腾讯集团而言，内部节省工时可能比工具收入更重要；需观察研发人员、交付周期和费用率是否变化，而不是用代码占比直接换算利润。",
        "action": "产品验证强、财务归因弱；作为能力基准，不因内部采用单独上修集团估值。",
        "refs": ("app-i24",),
    },
    {
        "subsector": "AI编程与软件开发",
        "company": "阿里巴巴",
        "ticker": "09988.HK",
        "role": "Qoder提供方和大型研发购买方",
        "evidence": "Qoder进入中国AI编程主要产品序列，但行业2025年收入仍不足1亿元，公开资料没有阿里外部席位和续费。",
        "financial_test": "产品价格与模型成本快速下降，短期更可能体现为内部研发效率和云生态黏性，而非对集团有意义的独立收入。",
        "action": "保持行业对照，不因产品存在计入应用组合。",
        "refs": ("app-i08",),
    },
    {
        "subsector": "AI编程与软件开发",
        "company": "百度",
        "ticker": "09888.HK",
        "role": "Comate提供方和云分发平台",
        "evidence": "Comate处于中国AI编程主要产品序列，但行业收入不足1亿元且公司没有披露外部产品收入与续费。",
        "financial_test": "需要把开发者使用、云调用和付费席位分开；使用量只有在提高云留存或形成收费后才影响估值。",
        "action": "产品位置可验证，商业化未验证；不进入A股应用组合。",
        "refs": ("app-i08",),
    },
    {
        "subsector": "AI编程与软件开发",
        "company": "软通动力",
        "ticker": "301236.SZ",
        "role": "软件交付购买方与AI工程服务提供方",
        "evidence": "公司已把AI用于需求、编码、测试和交付，并提出“人+Tokens”交付；同时服务阿里、蚂蚁、字节等模型客户。",
        "financial_test": "AI可能提高项目毛利，也可能压低传统人天收入。必须看到人均收入、交付周期、人员规模和项目毛利变化，当前‘显著提效’没有量化。",
        "action": "它是购买方效率传导的关键观察样本，未披露单位经济性前不把AI当独立增长曲线。",
        "refs": ("app-i32",),
    },
    {
        "subsector": "教育AI",
        "company": "视源股份",
        "ticker": "002841.SZ",
        "role": "教育显示、批阅硬件与AI软件提供方",
        "evidence": "学生作业智能批阅与学情一体机已投入市场，但公司未单列收入、学校数和续费。",
        "financial_test": "汇丰预测2026—2028年EPS 2.94/3.50/3.97元、目标价75.40元；华创预测归母净利润23.98/27.02/30.05亿元、目标价60元。两者都认为教育AI有贡献，但主控板传价和汽车电子同样重要。",
        "action": "估值分歧大且利润归因混合；只有AI教育软件付费、学校数和毛利单列后才提高AI权重。",
        "refs": ("app-i19", "app-i36", "app-i37"),
    },
    {
        "subsector": "教育AI",
        "company": "鸥玛软件",
        "ticker": "301185.SZ",
        "role": "考试测评与AI评卷提供方",
        "evidence": "2025年AI技术服务已作为部分考试合同的独立计价项，并按服务量收费；证券业协会2026—2028年考试服务项目中标5760万元。",
        "financial_test": "AI计价是强证据，但5760万元包含完整考试服务，不能全部算AI。需要拆AI服务量、单价、毛利以及其他考试客户复制。",
        "action": "教育组中商业模式最清楚的小市值候选之一，下一步优先补AI收入占比和续约。",
        "refs": ("app-i27",),
    },
    {
        "subsector": "教育AI",
        "company": "拓维信息",
        "ticker": "002261.SZ",
        "role": "教育考试软件、鸿蒙与AI软硬件提供方",
        "evidence": "公司计划在考试、教育、政务、交通和制造推进AI原生应用、智能体与边端硬件，但2025年年报没有拆出AI教育合同和收入。",
        "financial_test": "服务器、鸿蒙、行业软件和AI应用混合，必须按业务拆分；产品规划和生态合作不能直接推高教育应用利润。",
        "action": "市场热度高、收入纯度低；只作教育AI与算力混合标的，不纳入纯应用核心组合。",
        "refs": ("app-i07",),
    },
)


def expanded_company_rows() -> tuple[dict[str, Any], ...]:
    return APPLICATION_COMPANY_EXTENSION_RESEARCH


def direction_scores() -> Mapping[str, float]:
    return {str(row["name"]): float(row["score"]) for row in SUBSECTOR_RESEARCH}


def _ranking_table() -> str:
    rows = [
        "| 排名 | AI应用细分行业 | 配置优先级 | 已形成的付费证据 | 最大未解问题 | 当前投资判断 |",
        "|---:|---|---|---|---|---|",
    ]
    for rank, row in enumerate(
        sorted(SUBSECTOR_RESEARCH, key=lambda item: float(item["score"]), reverse=True),
        start=1,
    ):
        paid = str(row["market"]).split("；", 1)[0]
        priority = "第一梯队" if rank <= 3 else "第二梯队" if rank <= 6 else "观察梯队"
        rows.append(
            f"| {rank} | {row['name']} | {priority} | {paid} | "
            f"{row['capability']} | {row['investment']} |"
        )
    return "\n".join(rows)


def _subsector_cards() -> str:
    blocks: list[str] = []
    for row in sorted(
        SUBSECTOR_RESEARCH, key=lambda item: float(item["score"]), reverse=True
    ):
        refs = " ".join(_cite(str(ref)) for ref in row["refs"])
        blocks.append(
            f"#### 细分行业｜{row['name']}\n\n"
            f"##### 市场规模与转化阶段\n\n{row['market']} {row['stage']} {refs}\n\n"
            f"##### 提供方、产品和竞争格局\n\n{row['providers']} {row['competition']}\n\n"
            f"##### 购买方、合同与客户价值\n\n{row['buyers']}\n\n"
            f"**可核验案例。** {row['buyer_case']}\n\n"
            f"##### 当前能力、未来边界与财务传导\n\n{row['capability']}\n\n"
            f"##### 本行业总结\n\n**{row['investment']}**"
        )
    return "\n\n".join(blocks)


def build_application_industry_parts() -> dict[str, str]:
    return {
        "问题": (
            "AI应用不是一个同质行业。本节分别判断九个细分领域已经形成多大付费市场、"
            "还有哪些工作流未转化，提供方能做到什么、购买方为什么付钱、竞争格局与能力"
            "边界如何变化，以及哪些行业的增长最可能穿透到上市公司的收入、利润和现金流。"
        ),
        "研究方法与数据": (
            "行业市场只使用统计口径明确的监管、IDC、学术研究和公司披露。先区分部署覆盖、"
            "已确认AI收入和可服务支出池；只有分子分母属于同一产品、地域和期间时才计算转化。"
            "排序依次比较已付费市场、购买方投资回报证据、产品可复制性、竞争壁垒和上市公司"
            "财务可验证性；公开页给出第一、第二和观察梯队，不用主观小数分制造精确感。"
            "公司产品发布、客户案例、合同、上线、验收、收入、回款和续费逐级区分。"
            f" {_cite('app-i01')} {_cite('app-i02')} {_cite('app-i10')}"
        ),
        "研究与分析": (
            "下表先给行业层结论。企业管理、网络安全和办公文档最接近‘高频工作流＋明确付款人"
            "＋可持续责任’；医疗长期空间大但兑现慢；代码开发使用价值高却尚未形成与使用量"
            "相称的中国收入；教育已从覆盖验证进入付费模式验证，但单校收入和利润仍不足。行业好不等于股票便宜，具体公司仍需"
            "在下一实体接受合同、财务、现金流和估值二次筛选。\n\n"
            + _ranking_table()
            + "\n\n"
            + _subsector_cards()
        ),
        "总结": (
            "**行业层面看多企业管理软件与工业流程、网络安全、办公文档与企业知识；"
            "金融、医疗和教育列第二梯队；创意应用与AI编程暂不作为A股核心配置方向。** "
            "股票层面当前只把合合信息列为有价格缓冲的应用候选；鼎捷数智的合同证据清楚，"
            "但盈利、ROE和当前估值未通过，金山办公则是好公司但价格已超过独立核心区间。"
            "未披露AI独立收入、增量毛利和现金回款的公司，不给予AI估值溢价。"
        ),
    }
