from __future__ import annotations

"""PostgreSQL-only repository for the market-cap valuation tracker.

The tracker deliberately has no SQLite writer or generic domain-data fallback.
All mutations enter narrow SECURITY DEFINER functions which re-check the full
``financial_data`` authority token under lock.
"""

import hashlib
import json
from dataclasses import dataclass
from datetime import date, datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any, Callable


WORKBOOK_SHA256 = "453ded4b67ad53848ffd90ab27ddcad21ba3262d623e3946de613c414091e3e0"
WRITER_IDENTITY = "honghu_writer_financial_data"


class ValuationTrackerError(RuntimeError):
    pass


def canonical_json(value: Any) -> str:
    # Stable Python-side identity for local manifests and source de-duplication.
    # Database mutation hashes are always generated by PostgreSQL itself.
    return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)


def sha256_json(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def _jsonb(value: Any) -> Any:
    try:
        from psycopg.types.json import Jsonb

        return Jsonb(value)
    except ImportError:  # pragma: no cover - psycopg is required in production
        return canonical_json(value)


@dataclass(frozen=True)
class AuthorityToken:
    state: str
    cutover_epoch: str
    approval_reference: str
    state_revision: int


class ValuationTrackerRepository:
    def __init__(self, read_factory: Callable[[], Any], write_factory: Callable[[], Any]):
        self._read_factory = read_factory
        self._write_factory = write_factory

    @staticmethod
    def _dict_rows(cursor: Any) -> list[dict[str, Any]]:
        names = [column.name if hasattr(column, "name") else column[0] for column in cursor.description]
        return [dict(zip(names, row)) for row in cursor.fetchall()]

    def _authority(self) -> AuthorityToken:
        # The financial writer intentionally has no direct SELECT capability
        # on the operations control plane. Read the token with the reader,
        # then let every SECURITY DEFINER mutation re-check it under row lock.
        connection = self._read_factory()
        try:
            row = connection.execute(
                """SELECT state,cutover_epoch,approval_reference,state_revision
                     FROM operations.cutover_unit_authority
                    WHERE cutover_unit='financial_data'"""
            ).fetchone()
        finally:
            connection.close()
        if row is None or row[0] not in {"S3", "S4"} or not all(row[1:3]):
            raise ValuationTrackerError("financial_data authority is unavailable")
        return AuthorityToken(str(row[0]), str(row[1]), str(row[2]), int(row[3]))

    def committed_task_result(
        self, operation_scope: str, idempotency_key: str
    ) -> dict[str, Any] | None:
        """Return a completed scheduled logical window before external fetches.

        This is deliberately not used by mutation methods.  Mutations must
        always enter the server function so its canonical request hash can
        reject same-key/different-payload conflicts.
        """
        if operation_scope not in {
            "record_market_batch_v1",
            "record_market_skip_v1",
            "record_ai_candidates_v1",
        }:
            raise ValuationTrackerError("operation is not a scheduled task scope")
        connection = self._write_factory()
        try:
            authority = self._authority()
            row = connection.execute(
                """SELECT valuation_tracker.replay_task_result_v1(
                    %s,%s,%s,%s,%s,%s,%s)""",
                (
                    operation_scope,idempotency_key,WRITER_IDENTITY,
                    authority.state,authority.cutover_epoch,
                    authority.approval_reference,authority.state_revision,
                ),
            ).fetchone()
            connection.rollback()
            if row is None or row[0] is None:
                return None
            result = dict(row[0])
            result["idempotent_replay"] = True
            return result
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def resolve_seed_identities(self, seed: dict[str, Any]) -> dict[str, Any]:
        if seed.get("workbook_sha256") != WORKBOOK_SHA256 or len(seed.get("rows") or []) != 7:
            raise ValuationTrackerError("workbook seed is not the reviewed seven-row source")
        connection = self._read_factory()
        try:
            resolved: list[dict[str, Any]] = []
            for source in seed["rows"]:
                name = str(source["canonical_name"])
                ticker = str(source["canonical_ticker"]).upper()
                companies = connection.execute(
                    """SELECT (payload->>'id')::bigint,payload->>'name',upper(payload->>'ticker'),
                              payload->>'market',stable_key
                         FROM shared_identity.legacy_record
                        WHERE source_database='research.db' AND source_table='company'
                          AND formal_business_data=true AND payload->>'name'=%s
                          AND upper(payload->>'ticker')=%s""",
                    (name, ticker),
                ).fetchall()
                if len(companies) != 1:
                    raise ValuationTrackerError(f"company identity is missing or ambiguous: {name}/{ticker}")
                company_id, observed_name, observed_ticker, _, stable_key = companies[0]
                securities = connection.execute(
                    """SELECT (payload->>'id')::bigint,payload->>'canonical_name',upper(payload->>'ticker'),
                              payload->>'market',payload->>'research_company_id',stable_key
                         FROM shared_identity.legacy_record
                        WHERE source_database='financial.db' AND source_table='financial_security'
                          AND formal_business_data=true AND payload->>'research_company_id'=%s""",
                    (str(company_id),),
                ).fetchall()
                links = connection.execute(
                    """SELECT payload->>'security_id',payload->>'link_role'
                         FROM shared_identity.legacy_record
                        WHERE source_database='financial.db'
                          AND source_table='financial_security_company_link'
                          AND formal_business_data=true AND payload->>'research_company_id'=%s""",
                    (str(company_id),),
                ).fetchall()
                if len(securities) != 1 or len(links) != 1:
                    raise ValuationTrackerError(f"financial security/link is missing or ambiguous: {name}")
                security_id, security_name, security_ticker, _, linked_company_id, security_key = securities[0]
                if (
                    observed_name != name
                    or observed_ticker != ticker
                    or security_name != name
                    or security_ticker != ticker
                    or int(linked_company_id) != int(company_id)
                    or int(links[0][0]) != int(security_id)
                    or links[0][1] != "canonical"
                    or stable_key != security_key
                ):
                    raise ValuationTrackerError(f"company/security identity conflict: {name}")
                item = dict(source)
                item["company_id"] = int(company_id)
                item["security_id"] = int(security_id)
                resolved.append(item)
            if len({row["company_id"] for row in resolved}) != 7 or len({row["security_id"] for row in resolved}) != 7:
                raise ValuationTrackerError("resolved identities are not unique")
            payload = dict(seed)
            payload["rows"] = resolved
            payload["rows_sha256"] = sha256_json(resolved)
            return payload
        finally:
            connection.close()

    def seed_workbook(self, seed: dict[str, Any], *, actor: str, idempotency_key: str) -> dict[str, Any]:
        payload = self.resolve_seed_identities(seed)
        connection = self._write_factory()
        try:
            authority = self._authority()
            result = connection.execute(
                "SELECT valuation_tracker.seed_workbook_v1(%s::jsonb,%s,%s,%s,%s,%s,%s,%s)",
                (
                    _jsonb(payload), idempotency_key, WRITER_IDENTITY, authority.state,
                    authority.cutover_epoch, authority.approval_reference,
                    authority.state_revision, actor,
                ),
            ).fetchone()[0]
            connection.commit()
            return dict(result)
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def watchlist(self) -> list[dict[str, Any]]:
        """Return all cards, latest/previous AI versions and history in one SQL query."""
        connection = self._read_factory()
        try:
            cursor = connection.execute(
                """SELECT m.member_id,m.company_id,m.security_id,m.canonical_name,m.canonical_ticker,
                          m.market,m.board,m.display_order,m.revision,m.current_policy_revision,
                          p.researcher_ratio_threshold,p.ai_ratio_threshold,p.max_snapshot_age_hours,
                          to_jsonb(rv) researcher_version,to_jsonb(published_ai) published_ai_version,
                          to_jsonb(ai) latest_ai_version,
                          to_jsonb(prev_ai) previous_ai_version,to_jsonb(ms) market_snapshot,
                          coalesce(hist.history,'[]'::jsonb) valuation_history
                     FROM valuation_tracker.member m
                     JOIN valuation_tracker.alert_policy_revision p
                       ON p.member_id=m.member_id AND p.policy_revision=m.current_policy_revision
                     LEFT JOIN valuation_tracker.valuation_version rv
                       ON rv.version_id=m.current_researcher_version_id
                     LEFT JOIN valuation_tracker.valuation_version published_ai
                       ON published_ai.version_id=m.current_ai_version_id
                     LEFT JOIN LATERAL (
                         SELECT * FROM valuation_tracker.valuation_version v
                          WHERE v.member_id=m.member_id AND v.valuation_kind='ai'
                            AND v.status IN ('candidate','published')
                          ORDER BY v.created_at DESC,v.version_id DESC LIMIT 1
                     ) ai ON true
                     LEFT JOIN LATERAL (
                         SELECT * FROM valuation_tracker.valuation_version v
                          WHERE v.member_id=m.member_id AND v.valuation_kind='ai'
                            AND v.status IN ('candidate','published')
                            AND (ai.version_id IS NULL OR v.version_id<>ai.version_id)
                          ORDER BY v.created_at DESC,v.version_id DESC LIMIT 1
                     ) prev_ai ON true
                     LEFT JOIN LATERAL (
                         SELECT * FROM valuation_tracker.market_snapshot s
                          WHERE s.member_id=m.member_id
                          ORDER BY s.observed_at DESC,s.snapshot_id DESC LIMIT 1
                     ) ms ON true
                     LEFT JOIN LATERAL (
                         SELECT jsonb_agg(to_jsonb(v) ORDER BY v.created_at DESC,v.version_id DESC) history
                           FROM valuation_tracker.valuation_version v WHERE v.member_id=m.member_id
                     ) hist ON true
                    WHERE m.enabled ORDER BY m.display_order"""
            )
            rows = self._dict_rows(cursor)
            now = datetime.now(timezone.utc)
            for row in rows:
                self._decorate(row, now=now)
            return rows
        finally:
            connection.close()

    @staticmethod
    def _decorate(row: dict[str, Any], *, now: datetime) -> None:
        snapshot = row.get("market_snapshot") or {}
        market_cap = snapshot.get("market_cap_value")
        observed_at = snapshot.get("observed_at")
        if isinstance(observed_at, str):
            observed_at = datetime.fromisoformat(observed_at.replace("Z", "+00:00"))
        stale = True
        if isinstance(observed_at, datetime):
            stale = (now - observed_at.astimezone(timezone.utc)).total_seconds() > int(row["max_snapshot_age_hours"]) * 3600
        row["snapshot_stale"] = stale
        for key, threshold_key in (("researcher", "researcher_ratio_threshold"), ("ai", "ai_ratio_threshold")):
            version = row.get("researcher_version") if key == "researcher" else (
                row.get("published_ai_version") or row.get("latest_ai_version")
            )
            if key == "ai":
                row["ai_alert_version"] = version
            ratio = None
            reason = None
            alert = False
            if not version:
                reason = "暂无估值版本"
            elif not market_cap:
                reason = "暂无市值快照"
            elif snapshot.get("trading_status") == "suspended":
                reason = "证券停牌，当前不判断"
            elif snapshot.get("trading_status") != "trading":
                reason = "交易状态不可得，当前不判断"
            elif stale:
                reason = "市值快照已过期"
            elif snapshot.get("currency") != version.get("currency"):
                reason = "市值与估值币种不同，不能直接比较"
            else:
                ratio = float(Decimal(str(market_cap)) / Decimal(str(version["ceiling_value"])))
                alert = ratio >= float(row[threshold_key])
            row[f"{key}_ratio"] = ratio
            row[f"{key}_alert"] = alert
            row[f"{key}_comparison_note"] = reason
        latest = row.get("latest_ai_version") or {}
        previous = row.get("previous_ai_version") or {}
        change = None
        if (
            latest.get("ceiling_value") is not None
            and previous.get("ceiling_value") not in (None, 0)
            and latest.get("currency") == previous.get("currency")
        ):
            change = float((Decimal(str(latest["ceiling_value"])) / Decimal(str(previous["ceiling_value"])) - 1) * 100)
        row["ai_change_pct"] = change

    def edit_valuation(
        self, member_id: int, kind: str, payload: dict[str, Any], *, expected_revision: int,
        actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        return self._write_function(
            "valuation_tracker.edit_valuation_v1",
            (member_id, kind, _jsonb(payload), expected_revision),
            actor=actor, idempotency_key=idempotency_key,
        )

    def edit_policy(
        self, member_id: int, researcher_threshold: float, ai_threshold: float,
        max_age_hours: int, reason: str, *, expected_revision: int,
        actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        return self._write_function(
            "valuation_tracker.edit_alert_policy_v1",
            (member_id, researcher_threshold, ai_threshold, max_age_hours, reason, expected_revision),
            actor=actor, idempotency_key=idempotency_key,
        )

    def _write_function(
        self, function_name: str, prefix: tuple[Any, ...], *, actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        if function_name not in {
            "valuation_tracker.edit_valuation_v1", "valuation_tracker.edit_alert_policy_v1"
        }:
            raise ValuationTrackerError("unreviewed valuation tracker function")
        connection = self._write_factory()
        try:
            authority = self._authority()
            params = (*prefix, idempotency_key, WRITER_IDENTITY, authority.state,
                      authority.cutover_epoch, authority.approval_reference,
                      authority.state_revision, actor)
            placeholders = ",".join(["%s"] * len(params))
            result = connection.execute(f"SELECT {function_name}({placeholders})", params).fetchone()[0]
            connection.commit()
            return dict(result)
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def a_share_members(self) -> list[dict[str, Any]]:
        connection = self._read_factory()
        try:
            cursor = connection.execute(
                """SELECT member_id,security_id,canonical_name,canonical_ticker,market
                     FROM valuation_tracker.member
                    WHERE enabled AND market IN ('上海','深圳') ORDER BY display_order"""
            )
            rows = self._dict_rows(cursor)
            if len(rows) != 6:
                raise ValuationTrackerError("A-share watchlist must contain exactly six securities")
            return rows
        finally:
            connection.close()

    def record_market_batch(
        self, trade_date: date, slot: str, observed_at: datetime,
        calendar_provider: str, calendar_evidence: dict[str, Any], items: list[dict[str, Any]],
        *, actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        connection = self._write_factory()
        try:
            authority = self._authority()
            result = connection.execute(
                "SELECT valuation_tracker.record_market_batch_v1(%s,%s,%s,%s,%s::jsonb,%s::jsonb,%s,%s,%s,%s,%s,%s,%s)",
                (trade_date, slot, observed_at, calendar_provider, _jsonb(calendar_evidence), _jsonb(items),
                 idempotency_key, WRITER_IDENTITY, authority.state, authority.cutover_epoch,
                 authority.approval_reference, authority.state_revision, actor),
            ).fetchone()[0]
            connection.commit()
            return dict(result)
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def record_market_skip(
        self, trade_date: date, slot: str, calendar_provider: str,
        calendar_evidence: dict[str, Any], *, actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        connection = self._write_factory()
        try:
            authority = self._authority()
            result = connection.execute(
                "SELECT valuation_tracker.record_market_skip_v1(%s,%s,%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s)",
                (trade_date, slot, calendar_provider, _jsonb(calendar_evidence), idempotency_key,
                 WRITER_IDENTITY, authority.state, authority.cutover_epoch,
                 authority.approval_reference, authority.state_revision, actor),
            ).fetchone()[0]
            connection.commit()
            return dict(result)
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def record_ai_candidates(
        self, valuation_date: date, candidates: list[dict[str, Any]], *,
        prompt_sha256: str, model_name: str, actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        connection = self._write_factory()
        try:
            authority = self._authority()
            result = connection.execute(
                "SELECT valuation_tracker.record_ai_candidates_v1(%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (valuation_date, _jsonb(candidates), prompt_sha256, model_name,
                 idempotency_key, WRITER_IDENTITY, authority.state,
                 authority.cutover_epoch, authority.approval_reference,
                 authority.state_revision, actor),
            ).fetchone()[0]
            connection.commit()
            return dict(result)
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def record_ai_no_candidates(
        self, valuation_date: date, skipped: list[dict[str, Any]], *,
        prompt_sha256: str, model_name: str, actor: str, idempotency_key: str,
    ) -> dict[str, Any]:
        connection = self._write_factory()
        try:
            authority = self._authority()
            result = connection.execute(
                "SELECT valuation_tracker.record_ai_no_candidates_v1(%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (valuation_date, _jsonb(skipped), prompt_sha256, model_name,
                 idempotency_key, WRITER_IDENTITY, authority.state,
                 authority.cutover_epoch, authority.approval_reference,
                 authority.state_revision, actor),
            ).fetchone()[0]
            connection.commit()
            return dict(result)
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()


def load_seed(path: str | Path) -> dict[str, Any]:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if payload.get("schema_version") != "honghu.valuation_tracker.workbook_seed.v1":
        raise ValuationTrackerError("unsupported valuation tracker seed")
    return payload
